// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorship_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthorshipReport = `-- name: CreateAuthorshipReport :one
INSERT INTO app.authorship_reports (submission_id, interview_id, report)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::jsonb
)
RETURNING report_id, submission_id, interview_id, report, created_at
`

type CreateAuthorshipReportParams struct {
	SubmissionID pgtype.UUID `db:"submission_id" json:"submissionId"`
	InterviewID  pgtype.UUID `db:"interview_id" json:"interviewId"`
	Report       []byte      `db:"report" json:"report"`
}

func (q *Queries) CreateAuthorshipReport(ctx context.Context, arg CreateAuthorshipReportParams) (AppAuthorshipReport, error) {
	row := q.db.QueryRow(ctx, createAuthorshipReport, arg.SubmissionID, arg.InterviewID, arg.Report)
	var i AppAuthorshipReport
	err := row.Scan(
		&i.ReportID,
		&i.SubmissionID,
		&i.InterviewID,
		&i.Report,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorshipReportByID = `-- name: GetAuthorshipReportByID :one
SELECT report_id, submission_id, interview_id, report, created_at
FROM app.authorship_reports
WHERE report_id = $1::uuid
`

func (q *Queries) GetAuthorshipReportByID(ctx context.Context, reportID pgtype.UUID) (AppAuthorshipReport, error) {
	row := q.db.QueryRow(ctx, getAuthorshipReportByID, reportID)
	var i AppAuthorshipReport
	err := row.Scan(
		&i.ReportID,
		&i.SubmissionID,
		&i.InterviewID,
		&i.Report,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAuthorshipReportBySubmission = `-- name: GetLatestAuthorshipReportBySubmission :one
SELECT report_id, submission_id, interview_id, report, created_at
FROM app.authorship_reports
WHERE submission_id = $1::uuid
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAuthorshipReportBySubmission(ctx context.Context, submissionID pgtype.UUID) (AppAuthorshipReport, error) {
	row := q.db.QueryRow(ctx, getLatestAuthorshipReportBySubmission, submissionID)
	var i AppAuthorshipReport
	err := row.Scan(
		&i.ReportID,
		&i.SubmissionID,
		&i.InterviewID,
		&i.Report,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthorshipReportsBySubmission = `-- name: ListAuthorshipReportsBySubmission :many
SELECT report_id, submission_id, interview_id, report, created_at
FROM app.authorship_reports
WHERE submission_id = $1::uuid
ORDER BY created_at DESC
`

func (q *Queries) ListAuthorshipReportsBySubmission(ctx context.Context, submissionID pgtype.UUID) ([]AppAuthorshipReport, error) {
	rows, err := q.db.Query(ctx, listAuthorshipReportsBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppAuthorshipReport
	for rows.Next() {
		var i AppAuthorshipReport
		if err := rows.Scan(
			&i.ReportID,
			&i.SubmissionID,
			&i.InterviewID,
			&i.Report,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
