// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorship.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBaselineSampleToProfile = `-- name: AddBaselineSampleToProfile :exec
INSERT INTO app.student_profile_baseline_samples (
    student_profile_version_id,
    student_writing_sample_id
)
VALUES (
    $1::uuid,
    $2::uuid
)
ON CONFLICT DO NOTHING
`

type AddBaselineSampleToProfileParams struct {
	StudentProfileVersionID pgtype.UUID `db:"student_profile_version_id" json:"studentProfileVersionId"`
	StudentWritingSampleID  pgtype.UUID `db:"student_writing_sample_id" json:"studentWritingSampleId"`
}

func (q *Queries) AddBaselineSampleToProfile(ctx context.Context, arg AddBaselineSampleToProfileParams) error {
	_, err := q.db.Exec(ctx, addBaselineSampleToProfile, arg.StudentProfileVersionID, arg.StudentWritingSampleID)
	return err
}

const createAuthorshipAnalysis = `-- name: CreateAuthorshipAnalysis :one

INSERT INTO app.authorship_analyses (
    student_id,
    student_writing_sample_id,
    student_profile_version_id,
    discrepancy_level,
    stylometric_distance,
    embedding_distance,
    feature_deltas,
    explanation,
    recommendation,
    model_version
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::app.discrepancy_level,
    $5,
    $6,
    $7,
    $8,
    $9::app.authorship_recommendation,
    $10
)
RETURNING authorship_analysis_id, student_id, student_writing_sample_id, student_profile_version_id, discrepancy_level, stylometric_distance, embedding_distance, feature_deltas, explanation, recommendation, model_version, created_at
`

type CreateAuthorshipAnalysisParams struct {
	StudentID               pgtype.UUID                 `db:"student_id" json:"studentId"`
	StudentWritingSampleID  pgtype.UUID                 `db:"student_writing_sample_id" json:"studentWritingSampleId"`
	StudentProfileVersionID pgtype.UUID                 `db:"student_profile_version_id" json:"studentProfileVersionId"`
	DiscrepancyLevel        AppDiscrepancyLevel         `db:"discrepancy_level" json:"discrepancyLevel"`
	StylometricDistance     pgtype.Numeric              `db:"stylometric_distance" json:"stylometricDistance"`
	EmbeddingDistance       pgtype.Numeric              `db:"embedding_distance" json:"embeddingDistance"`
	FeatureDeltas           []byte                      `db:"feature_deltas" json:"featureDeltas"`
	Explanation             []byte                      `db:"explanation" json:"explanation"`
	Recommendation          AppAuthorshipRecommendation `db:"recommendation" json:"recommendation"`
	ModelVersion            pgtype.Text                 `db:"model_version" json:"modelVersion"`
}

// Authorship analyses
func (q *Queries) CreateAuthorshipAnalysis(ctx context.Context, arg CreateAuthorshipAnalysisParams) (AppAuthorshipAnalysis, error) {
	row := q.db.QueryRow(ctx, createAuthorshipAnalysis,
		arg.StudentID,
		arg.StudentWritingSampleID,
		arg.StudentProfileVersionID,
		arg.DiscrepancyLevel,
		arg.StylometricDistance,
		arg.EmbeddingDistance,
		arg.FeatureDeltas,
		arg.Explanation,
		arg.Recommendation,
		arg.ModelVersion,
	)
	var i AppAuthorshipAnalysis
	err := row.Scan(
		&i.AuthorshipAnalysisID,
		&i.StudentID,
		&i.StudentWritingSampleID,
		&i.StudentProfileVersionID,
		&i.DiscrepancyLevel,
		&i.StylometricDistance,
		&i.EmbeddingDistance,
		&i.FeatureDeltas,
		&i.Explanation,
		&i.Recommendation,
		&i.ModelVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthorshipReview = `-- name: CreateAuthorshipReview :one

INSERT INTO app.authorship_reviews (
    authorship_analysis_id,
    teacher_id,
    review_status,
    teacher_decision,
    notes
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::app.review_status,
    $4::app.teacher_decision,
    $5
)
RETURNING authorship_review_id, authorship_analysis_id, teacher_id, review_status, teacher_decision, notes, reviewed_at, created_at
`

type CreateAuthorshipReviewParams struct {
	AuthorshipAnalysisID pgtype.UUID        `db:"authorship_analysis_id" json:"authorshipAnalysisId"`
	TeacherID            pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	ReviewStatus         AppReviewStatus    `db:"review_status" json:"reviewStatus"`
	TeacherDecision      AppTeacherDecision `db:"teacher_decision" json:"teacherDecision"`
	Notes                pgtype.Text        `db:"notes" json:"notes"`
}

// Reviews
func (q *Queries) CreateAuthorshipReview(ctx context.Context, arg CreateAuthorshipReviewParams) (AppAuthorshipReview, error) {
	row := q.db.QueryRow(ctx, createAuthorshipReview,
		arg.AuthorshipAnalysisID,
		arg.TeacherID,
		arg.ReviewStatus,
		arg.TeacherDecision,
		arg.Notes,
	)
	var i AppAuthorshipReview
	err := row.Scan(
		&i.AuthorshipReviewID,
		&i.AuthorshipAnalysisID,
		&i.TeacherID,
		&i.ReviewStatus,
		&i.TeacherDecision,
		&i.Notes,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthorshipViva = `-- name: CreateAuthorshipViva :one

INSERT INTO app.authorship_vivas (
    authorship_analysis_id,
    generated_questions,
    transcript,
    conceptual_alignment_summary,
    alignment_level,
    alignment_notes
)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5::app.alignment_level,
    $6
)
RETURNING authorship_viva_id, authorship_analysis_id, generated_questions, transcript, conceptual_alignment_summary, alignment_level, alignment_notes, created_at
`

type CreateAuthorshipVivaParams struct {
	AuthorshipAnalysisID       pgtype.UUID       `db:"authorship_analysis_id" json:"authorshipAnalysisId"`
	GeneratedQuestions         []byte            `db:"generated_questions" json:"generatedQuestions"`
	Transcript                 pgtype.Text       `db:"transcript" json:"transcript"`
	ConceptualAlignmentSummary []byte            `db:"conceptual_alignment_summary" json:"conceptualAlignmentSummary"`
	AlignmentLevel             AppAlignmentLevel `db:"alignment_level" json:"alignmentLevel"`
	AlignmentNotes             pgtype.Text       `db:"alignment_notes" json:"alignmentNotes"`
}

// Vivas
func (q *Queries) CreateAuthorshipViva(ctx context.Context, arg CreateAuthorshipVivaParams) (AppAuthorshipViva, error) {
	row := q.db.QueryRow(ctx, createAuthorshipViva,
		arg.AuthorshipAnalysisID,
		arg.GeneratedQuestions,
		arg.Transcript,
		arg.ConceptualAlignmentSummary,
		arg.AlignmentLevel,
		arg.AlignmentNotes,
	)
	var i AppAuthorshipViva
	err := row.Scan(
		&i.AuthorshipVivaID,
		&i.AuthorshipAnalysisID,
		&i.GeneratedQuestions,
		&i.Transcript,
		&i.ConceptualAlignmentSummary,
		&i.AlignmentLevel,
		&i.AlignmentNotes,
		&i.CreatedAt,
	)
	return i, err
}

const createStudentProfileVersion = `-- name: CreateStudentProfileVersion :one

INSERT INTO app.student_profile_versions (
    student_id,
    semester,
    version,
    profile_status,
    feature_summary,
    model_version
)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4::app.profile_status,
    $5,
    $6
)
RETURNING student_profile_version_id, student_id, semester, version, profile_status, feature_summary, model_version, created_at
`

type CreateStudentProfileVersionParams struct {
	StudentID      pgtype.UUID      `db:"student_id" json:"studentId"`
	Semester       string           `db:"semester" json:"semester"`
	Version        int32            `db:"version" json:"version"`
	ProfileStatus  AppProfileStatus `db:"profile_status" json:"profileStatus"`
	FeatureSummary []byte           `db:"feature_summary" json:"featureSummary"`
	ModelVersion   pgtype.Text      `db:"model_version" json:"modelVersion"`
}

// Profiles and baseline links
func (q *Queries) CreateStudentProfileVersion(ctx context.Context, arg CreateStudentProfileVersionParams) (AppStudentProfileVersion, error) {
	row := q.db.QueryRow(ctx, createStudentProfileVersion,
		arg.StudentID,
		arg.Semester,
		arg.Version,
		arg.ProfileStatus,
		arg.FeatureSummary,
		arg.ModelVersion,
	)
	var i AppStudentProfileVersion
	err := row.Scan(
		&i.StudentProfileVersionID,
		&i.StudentID,
		&i.Semester,
		&i.Version,
		&i.ProfileStatus,
		&i.FeatureSummary,
		&i.ModelVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createStudentWritingSample = `-- name: CreateStudentWritingSample :one

INSERT INTO app.student_writing_samples (
    student_id,
    semester,
    assignment_name,
    source_type,
    written_at,
    text_content,
    is_teacher_verified,
    raw_features
)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4::app.writing_source_type,
    $5,
    $6,
    $7,
    $8
)
RETURNING student_writing_sample_id, student_id, semester, assignment_name, source_type, written_at, text_content, is_teacher_verified, raw_features, created_at
`

type CreateStudentWritingSampleParams struct {
	StudentID         pgtype.UUID          `db:"student_id" json:"studentId"`
	Semester          string               `db:"semester" json:"semester"`
	AssignmentName    pgtype.Text          `db:"assignment_name" json:"assignmentName"`
	SourceType        AppWritingSourceType `db:"source_type" json:"sourceType"`
	WrittenAt         pgtype.Timestamptz   `db:"written_at" json:"writtenAt"`
	TextContent       string               `db:"text_content" json:"textContent"`
	IsTeacherVerified bool                 `db:"is_teacher_verified" json:"isTeacherVerified"`
	RawFeatures       []byte               `db:"raw_features" json:"rawFeatures"`
}

// Student writing samples
func (q *Queries) CreateStudentWritingSample(ctx context.Context, arg CreateStudentWritingSampleParams) (AppStudentWritingSample, error) {
	row := q.db.QueryRow(ctx, createStudentWritingSample,
		arg.StudentID,
		arg.Semester,
		arg.AssignmentName,
		arg.SourceType,
		arg.WrittenAt,
		arg.TextContent,
		arg.IsTeacherVerified,
		arg.RawFeatures,
	)
	var i AppStudentWritingSample
	err := row.Scan(
		&i.StudentWritingSampleID,
		&i.StudentID,
		&i.Semester,
		&i.AssignmentName,
		&i.SourceType,
		&i.WrittenAt,
		&i.TextContent,
		&i.IsTeacherVerified,
		&i.RawFeatures,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveProfileForStudentSemester = `-- name: GetActiveProfileForStudentSemester :one
SELECT student_profile_version_id, student_id, semester, version, profile_status, feature_summary, model_version, created_at
FROM app.student_profile_versions
WHERE student_id = $1::uuid
  AND semester = $2
  AND profile_status = 'active'
ORDER BY version DESC
LIMIT 1
`

type GetActiveProfileForStudentSemesterParams struct {
	StudentID pgtype.UUID `db:"student_id" json:"studentId"`
	Semester  string      `db:"semester" json:"semester"`
}

func (q *Queries) GetActiveProfileForStudentSemester(ctx context.Context, arg GetActiveProfileForStudentSemesterParams) (AppStudentProfileVersion, error) {
	row := q.db.QueryRow(ctx, getActiveProfileForStudentSemester, arg.StudentID, arg.Semester)
	var i AppStudentProfileVersion
	err := row.Scan(
		&i.StudentProfileVersionID,
		&i.StudentID,
		&i.Semester,
		&i.Version,
		&i.ProfileStatus,
		&i.FeatureSummary,
		&i.ModelVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorshipAnalysisByID = `-- name: GetAuthorshipAnalysisByID :one
SELECT authorship_analysis_id, student_id, student_writing_sample_id, student_profile_version_id, discrepancy_level, stylometric_distance, embedding_distance, feature_deltas, explanation, recommendation, model_version, created_at
FROM app.authorship_analyses
WHERE authorship_analysis_id = $1::uuid
`

func (q *Queries) GetAuthorshipAnalysisByID(ctx context.Context, authorshipAnalysisID pgtype.UUID) (AppAuthorshipAnalysis, error) {
	row := q.db.QueryRow(ctx, getAuthorshipAnalysisByID, authorshipAnalysisID)
	var i AppAuthorshipAnalysis
	err := row.Scan(
		&i.AuthorshipAnalysisID,
		&i.StudentID,
		&i.StudentWritingSampleID,
		&i.StudentProfileVersionID,
		&i.DiscrepancyLevel,
		&i.StylometricDistance,
		&i.EmbeddingDistance,
		&i.FeatureDeltas,
		&i.Explanation,
		&i.Recommendation,
		&i.ModelVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorshipReviewByID = `-- name: GetAuthorshipReviewByID :one
SELECT authorship_review_id, authorship_analysis_id, teacher_id, review_status, teacher_decision, notes, reviewed_at, created_at
FROM app.authorship_reviews
WHERE authorship_review_id = $1::uuid
`

func (q *Queries) GetAuthorshipReviewByID(ctx context.Context, authorshipReviewID pgtype.UUID) (AppAuthorshipReview, error) {
	row := q.db.QueryRow(ctx, getAuthorshipReviewByID, authorshipReviewID)
	var i AppAuthorshipReview
	err := row.Scan(
		&i.AuthorshipReviewID,
		&i.AuthorshipAnalysisID,
		&i.TeacherID,
		&i.ReviewStatus,
		&i.TeacherDecision,
		&i.Notes,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorshipVivaByAnalysisID = `-- name: GetAuthorshipVivaByAnalysisID :one
SELECT authorship_viva_id, authorship_analysis_id, generated_questions, transcript, conceptual_alignment_summary, alignment_level, alignment_notes, created_at
FROM app.authorship_vivas
WHERE authorship_analysis_id = $1::uuid
`

func (q *Queries) GetAuthorshipVivaByAnalysisID(ctx context.Context, authorshipAnalysisID pgtype.UUID) (AppAuthorshipViva, error) {
	row := q.db.QueryRow(ctx, getAuthorshipVivaByAnalysisID, authorshipAnalysisID)
	var i AppAuthorshipViva
	err := row.Scan(
		&i.AuthorshipVivaID,
		&i.AuthorshipAnalysisID,
		&i.GeneratedQuestions,
		&i.Transcript,
		&i.ConceptualAlignmentSummary,
		&i.AlignmentLevel,
		&i.AlignmentNotes,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorshipVivaByID = `-- name: GetAuthorshipVivaByID :one
SELECT authorship_viva_id, authorship_analysis_id, generated_questions, transcript, conceptual_alignment_summary, alignment_level, alignment_notes, created_at
FROM app.authorship_vivas
WHERE authorship_viva_id = $1::uuid
`

func (q *Queries) GetAuthorshipVivaByID(ctx context.Context, authorshipVivaID pgtype.UUID) (AppAuthorshipViva, error) {
	row := q.db.QueryRow(ctx, getAuthorshipVivaByID, authorshipVivaID)
	var i AppAuthorshipViva
	err := row.Scan(
		&i.AuthorshipVivaID,
		&i.AuthorshipAnalysisID,
		&i.GeneratedQuestions,
		&i.Transcript,
		&i.ConceptualAlignmentSummary,
		&i.AlignmentLevel,
		&i.AlignmentNotes,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentWritingSampleByID = `-- name: GetStudentWritingSampleByID :one
SELECT student_writing_sample_id, student_id, semester, assignment_name, source_type, written_at, text_content, is_teacher_verified, raw_features, created_at
FROM app.student_writing_samples
WHERE student_writing_sample_id = $1::uuid
`

func (q *Queries) GetStudentWritingSampleByID(ctx context.Context, studentWritingSampleID pgtype.UUID) (AppStudentWritingSample, error) {
	row := q.db.QueryRow(ctx, getStudentWritingSampleByID, studentWritingSampleID)
	var i AppStudentWritingSample
	err := row.Scan(
		&i.StudentWritingSampleID,
		&i.StudentID,
		&i.Semester,
		&i.AssignmentName,
		&i.SourceType,
		&i.WrittenAt,
		&i.TextContent,
		&i.IsTeacherVerified,
		&i.RawFeatures,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthorshipAnalysesForSample = `-- name: ListAuthorshipAnalysesForSample :many
SELECT authorship_analysis_id, student_id, student_writing_sample_id, student_profile_version_id, discrepancy_level, stylometric_distance, embedding_distance, feature_deltas, explanation, recommendation, model_version, created_at
FROM app.authorship_analyses
WHERE student_writing_sample_id = $1::uuid
ORDER BY created_at DESC
`

func (q *Queries) ListAuthorshipAnalysesForSample(ctx context.Context, studentWritingSampleID pgtype.UUID) ([]AppAuthorshipAnalysis, error) {
	rows, err := q.db.Query(ctx, listAuthorshipAnalysesForSample, studentWritingSampleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppAuthorshipAnalysis
	for rows.Next() {
		var i AppAuthorshipAnalysis
		if err := rows.Scan(
			&i.AuthorshipAnalysisID,
			&i.StudentID,
			&i.StudentWritingSampleID,
			&i.StudentProfileVersionID,
			&i.DiscrepancyLevel,
			&i.StylometricDistance,
			&i.EmbeddingDistance,
			&i.FeatureDeltas,
			&i.Explanation,
			&i.Recommendation,
			&i.ModelVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBaselineSamplesForProfile = `-- name: ListBaselineSamplesForProfile :many
SELECT s.student_writing_sample_id, s.student_id, s.semester, s.assignment_name, s.source_type, s.written_at, s.text_content, s.is_teacher_verified, s.raw_features, s.created_at
FROM app.student_profile_baseline_samples b
JOIN app.student_writing_samples s
  ON s.student_writing_sample_id = b.student_writing_sample_id
WHERE b.student_profile_version_id = $1::uuid
ORDER BY s.created_at ASC
`

func (q *Queries) ListBaselineSamplesForProfile(ctx context.Context, studentProfileVersionID pgtype.UUID) ([]AppStudentWritingSample, error) {
	rows, err := q.db.Query(ctx, listBaselineSamplesForProfile, studentProfileVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppStudentWritingSample
	for rows.Next() {
		var i AppStudentWritingSample
		if err := rows.Scan(
			&i.StudentWritingSampleID,
			&i.StudentID,
			&i.Semester,
			&i.AssignmentName,
			&i.SourceType,
			&i.WrittenAt,
			&i.TextContent,
			&i.IsTeacherVerified,
			&i.RawFeatures,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBaselineSamplesForStudentSemester = `-- name: ListBaselineSamplesForStudentSemester :many
SELECT student_writing_sample_id, student_id, semester, assignment_name, source_type, written_at, text_content, is_teacher_verified, raw_features, created_at
FROM app.student_writing_samples
WHERE student_id = $1::uuid
  AND semester = $2
  AND source_type IN ('baseline_in_class', 'baseline_supervised')
`

type ListBaselineSamplesForStudentSemesterParams struct {
	StudentID pgtype.UUID `db:"student_id" json:"studentId"`
	Semester  string      `db:"semester" json:"semester"`
}

func (q *Queries) ListBaselineSamplesForStudentSemester(ctx context.Context, arg ListBaselineSamplesForStudentSemesterParams) ([]AppStudentWritingSample, error) {
	rows, err := q.db.Query(ctx, listBaselineSamplesForStudentSemester, arg.StudentID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppStudentWritingSample
	for rows.Next() {
		var i AppStudentWritingSample
		if err := rows.Scan(
			&i.StudentWritingSampleID,
			&i.StudentID,
			&i.Semester,
			&i.AssignmentName,
			&i.SourceType,
			&i.WrittenAt,
			&i.TextContent,
			&i.IsTeacherVerified,
			&i.RawFeatures,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAuthorshipReviewsForTeacher = `-- name: ListPendingAuthorshipReviewsForTeacher :many
SELECT ar.authorship_review_id, ar.authorship_analysis_id, ar.teacher_id, ar.review_status, ar.teacher_decision, ar.notes, ar.reviewed_at, ar.created_at
FROM app.authorship_reviews ar
JOIN app.authorship_analyses aa
  ON ar.authorship_analysis_id = aa.authorship_analysis_id
WHERE ar.teacher_id = $1::uuid
  AND ar.review_status = 'pending'
ORDER BY aa.created_at DESC
`

func (q *Queries) ListPendingAuthorshipReviewsForTeacher(ctx context.Context, teacherID pgtype.UUID) ([]AppAuthorshipReview, error) {
	rows, err := q.db.Query(ctx, listPendingAuthorshipReviewsForTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppAuthorshipReview
	for rows.Next() {
		var i AppAuthorshipReview
		if err := rows.Scan(
			&i.AuthorshipReviewID,
			&i.AuthorshipAnalysisID,
			&i.TeacherID,
			&i.ReviewStatus,
			&i.TeacherDecision,
			&i.Notes,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStudentProfileStatus = `-- name: SetStudentProfileStatus :exec
UPDATE app.student_profile_versions
SET profile_status = $1::app.profile_status
WHERE student_profile_version_id = $2::uuid
`

type SetStudentProfileStatusParams struct {
	ProfileStatus           AppProfileStatus `db:"profile_status" json:"profileStatus"`
	StudentProfileVersionID pgtype.UUID      `db:"student_profile_version_id" json:"studentProfileVersionId"`
}

func (q *Queries) SetStudentProfileStatus(ctx context.Context, arg SetStudentProfileStatusParams) error {
	_, err := q.db.Exec(ctx, setStudentProfileStatus, arg.ProfileStatus, arg.StudentProfileVersionID)
	return err
}

const updateAuthorshipReview = `-- name: UpdateAuthorshipReview :one
UPDATE app.authorship_reviews
SET review_status    = $1::app.review_status,
    teacher_decision = $2::app.teacher_decision,
    notes           = $3,
    reviewed_at     = CASE
        WHEN $1::app.review_status IN ('reviewed', 'resolved') THEN NOW()
        ELSE reviewed_at
    END
WHERE authorship_review_id = $4::uuid
RETURNING authorship_review_id, authorship_analysis_id, teacher_id, review_status, teacher_decision, notes, reviewed_at, created_at
`

type UpdateAuthorshipReviewParams struct {
	ReviewStatus       AppReviewStatus    `db:"review_status" json:"reviewStatus"`
	TeacherDecision    AppTeacherDecision `db:"teacher_decision" json:"teacherDecision"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	AuthorshipReviewID pgtype.UUID        `db:"authorship_review_id" json:"authorshipReviewId"`
}

func (q *Queries) UpdateAuthorshipReview(ctx context.Context, arg UpdateAuthorshipReviewParams) (AppAuthorshipReview, error) {
	row := q.db.QueryRow(ctx, updateAuthorshipReview,
		arg.ReviewStatus,
		arg.TeacherDecision,
		arg.Notes,
		arg.AuthorshipReviewID,
	)
	var i AppAuthorshipReview
	err := row.Scan(
		&i.AuthorshipReviewID,
		&i.AuthorshipAnalysisID,
		&i.TeacherID,
		&i.ReviewStatus,
		&i.TeacherDecision,
		&i.Notes,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}
