// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClass = `-- name: CreateClass :one
INSERT INTO app.classes (teacher_id, name, class_code)
VALUES ($1::uuid, $2, $3)
RETURNING class_id, teacher_id, name, class_code, created_at, updated_at
`

type CreateClassParams struct {
	TeacherID pgtype.UUID `db:"teacher_id" json:"teacherId"`
	Name      string      `db:"name" json:"name"`
	ClassCode string      `db:"class_code" json:"classCode"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (AppClass, error) {
	row := q.db.QueryRow(ctx, createClass, arg.TeacherID, arg.Name, arg.ClassCode)
	var i AppClass
	err := row.Scan(
		&i.ClassID,
		&i.TeacherID,
		&i.Name,
		&i.ClassCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM app.classes
WHERE class_id = $1::uuid
`

func (q *Queries) DeleteClass(ctx context.Context, classID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClass, classID)
	return err
}

const getClassByCode = `-- name: GetClassByCode :one
SELECT class_id, teacher_id, name, class_code, created_at, updated_at
FROM app.classes
WHERE class_code = $1
`

func (q *Queries) GetClassByCode(ctx context.Context, classCode string) (AppClass, error) {
	row := q.db.QueryRow(ctx, getClassByCode, classCode)
	var i AppClass
	err := row.Scan(
		&i.ClassID,
		&i.TeacherID,
		&i.Name,
		&i.ClassCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassByID = `-- name: GetClassByID :one
SELECT class_id, teacher_id, name, class_code, created_at, updated_at
FROM app.classes
WHERE class_id = $1::uuid
`

func (q *Queries) GetClassByID(ctx context.Context, classID pgtype.UUID) (AppClass, error) {
	row := q.db.QueryRow(ctx, getClassByID, classID)
	var i AppClass
	err := row.Scan(
		&i.ClassID,
		&i.TeacherID,
		&i.Name,
		&i.ClassCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClassesByTeacher = `-- name: ListClassesByTeacher :many
SELECT class_id, teacher_id, name, class_code, created_at, updated_at
FROM app.classes
WHERE teacher_id = $1::uuid
ORDER BY name ASC, created_at DESC
`

func (q *Queries) ListClassesByTeacher(ctx context.Context, teacherID pgtype.UUID) ([]AppClass, error) {
	rows, err := q.db.Query(ctx, listClassesByTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppClass
	for rows.Next() {
		var i AppClass
		if err := rows.Scan(
			&i.ClassID,
			&i.TeacherID,
			&i.Name,
			&i.ClassCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE app.classes
SET name       = $1,
    class_code = $2,
    updated_at  = NOW()
WHERE class_id = $3::uuid
RETURNING class_id, teacher_id, name, class_code, created_at, updated_at
`

type UpdateClassParams struct {
	Name      string      `db:"name" json:"name"`
	ClassCode string      `db:"class_code" json:"classCode"`
	ClassID   pgtype.UUID `db:"class_id" json:"classId"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (AppClass, error) {
	row := q.db.QueryRow(ctx, updateClass, arg.Name, arg.ClassCode, arg.ClassID)
	var i AppClass
	err := row.Scan(
		&i.ClassID,
		&i.TeacherID,
		&i.Name,
		&i.ClassCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
