// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: concept_tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConceptTag = `-- name: CreateConceptTag :one
INSERT INTO app.concept_tags (
    name,
    display_name,
    description,
    curriculum_descriptor_id
)
VALUES (
    $1,
    $2,
    $3,
    $4::uuid
)
RETURNING concept_tag_id, name, display_name, description, curriculum_descriptor_id, created_at, updated_at
`

type CreateConceptTagParams struct {
	Name                   string      `db:"name" json:"name"`
	DisplayName            pgtype.Text `db:"display_name" json:"displayName"`
	Description            pgtype.Text `db:"description" json:"description"`
	CurriculumDescriptorID pgtype.UUID `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
}

func (q *Queries) CreateConceptTag(ctx context.Context, arg CreateConceptTagParams) (AppConceptTag, error) {
	row := q.db.QueryRow(ctx, createConceptTag,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.CurriculumDescriptorID,
	)
	var i AppConceptTag
	err := row.Scan(
		&i.ConceptTagID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CurriculumDescriptorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConceptTagByID = `-- name: GetConceptTagByID :one
SELECT concept_tag_id, name, display_name, description, curriculum_descriptor_id, created_at, updated_at
FROM app.concept_tags
WHERE concept_tag_id = $1::uuid
`

func (q *Queries) GetConceptTagByID(ctx context.Context, conceptTagID pgtype.UUID) (AppConceptTag, error) {
	row := q.db.QueryRow(ctx, getConceptTagByID, conceptTagID)
	var i AppConceptTag
	err := row.Scan(
		&i.ConceptTagID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CurriculumDescriptorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConceptTagByName = `-- name: GetConceptTagByName :one
SELECT concept_tag_id, name, display_name, description, curriculum_descriptor_id, created_at, updated_at
FROM app.concept_tags
WHERE curriculum_descriptor_id = $1::uuid
  AND name = $2
`

type GetConceptTagByNameParams struct {
	CurriculumDescriptorID pgtype.UUID `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	Name                   string      `db:"name" json:"name"`
}

func (q *Queries) GetConceptTagByName(ctx context.Context, arg GetConceptTagByNameParams) (AppConceptTag, error) {
	row := q.db.QueryRow(ctx, getConceptTagByName, arg.CurriculumDescriptorID, arg.Name)
	var i AppConceptTag
	err := row.Scan(
		&i.ConceptTagID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CurriculumDescriptorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConceptTagsByDescriptor = `-- name: ListConceptTagsByDescriptor :many
SELECT concept_tag_id, name, display_name, description, curriculum_descriptor_id, created_at, updated_at
FROM app.concept_tags
WHERE curriculum_descriptor_id = $1::uuid
ORDER BY name ASC
`

func (q *Queries) ListConceptTagsByDescriptor(ctx context.Context, curriculumDescriptorID pgtype.UUID) ([]AppConceptTag, error) {
	rows, err := q.db.Query(ctx, listConceptTagsByDescriptor, curriculumDescriptorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppConceptTag
	for rows.Next() {
		var i AppConceptTag
		if err := rows.Scan(
			&i.ConceptTagID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CurriculumDescriptorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConceptTag = `-- name: UpdateConceptTag :one
UPDATE app.concept_tags
SET display_name = $1,
    description = $2,
    updated_at = NOW()
WHERE concept_tag_id = $3::uuid
RETURNING concept_tag_id, name, display_name, description, curriculum_descriptor_id, created_at, updated_at
`

type UpdateConceptTagParams struct {
	DisplayName  pgtype.Text `db:"display_name" json:"displayName"`
	Description  pgtype.Text `db:"description" json:"description"`
	ConceptTagID pgtype.UUID `db:"concept_tag_id" json:"conceptTagId"`
}

func (q *Queries) UpdateConceptTag(ctx context.Context, arg UpdateConceptTagParams) (AppConceptTag, error) {
	row := q.db.QueryRow(ctx, updateConceptTag, arg.DisplayName, arg.Description, arg.ConceptTagID)
	var i AppConceptTag
	err := row.Scan(
		&i.ConceptTagID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.CurriculumDescriptorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
