// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: criterion_evidence.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCriterionEvidence = `-- name: CreateCriterionEvidence :one
INSERT INTO app.criterion_evidence (
    interview_summary_id,
    rubric_criterion_id,
    level,
    evidence_text,
    model_confidence
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5
)
RETURNING criterion_evidence_id, interview_summary_id, rubric_criterion_id, level, evidence_text, model_confidence, created_at
`

type CreateCriterionEvidenceParams struct {
	InterviewSummaryID pgtype.UUID    `db:"interview_summary_id" json:"interviewSummaryId"`
	RubricCriterionID  pgtype.UUID    `db:"rubric_criterion_id" json:"rubricCriterionId"`
	Level              pgtype.Text    `db:"level" json:"level"`
	EvidenceText       pgtype.Text    `db:"evidence_text" json:"evidenceText"`
	ModelConfidence    pgtype.Numeric `db:"model_confidence" json:"modelConfidence"`
}

func (q *Queries) CreateCriterionEvidence(ctx context.Context, arg CreateCriterionEvidenceParams) (AppCriterionEvidence, error) {
	row := q.db.QueryRow(ctx, createCriterionEvidence,
		arg.InterviewSummaryID,
		arg.RubricCriterionID,
		arg.Level,
		arg.EvidenceText,
		arg.ModelConfidence,
	)
	var i AppCriterionEvidence
	err := row.Scan(
		&i.CriterionEvidenceID,
		&i.InterviewSummaryID,
		&i.RubricCriterionID,
		&i.Level,
		&i.EvidenceText,
		&i.ModelConfidence,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCriterionEvidenceBySummaryID = `-- name: DeleteCriterionEvidenceBySummaryID :exec
DELETE FROM app.criterion_evidence
WHERE interview_summary_id = $1::uuid
`

func (q *Queries) DeleteCriterionEvidenceBySummaryID(ctx context.Context, interviewSummaryID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCriterionEvidenceBySummaryID, interviewSummaryID)
	return err
}

const getCriterionEvidenceByCriterionID = `-- name: GetCriterionEvidenceByCriterionID :many
SELECT criterion_evidence_id, interview_summary_id, rubric_criterion_id, level, evidence_text, model_confidence, created_at
FROM app.criterion_evidence
WHERE rubric_criterion_id = $1::uuid
ORDER BY created_at ASC
`

func (q *Queries) GetCriterionEvidenceByCriterionID(ctx context.Context, rubricCriterionID pgtype.UUID) ([]AppCriterionEvidence, error) {
	rows, err := q.db.Query(ctx, getCriterionEvidenceByCriterionID, rubricCriterionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppCriterionEvidence
	for rows.Next() {
		var i AppCriterionEvidence
		if err := rows.Scan(
			&i.CriterionEvidenceID,
			&i.InterviewSummaryID,
			&i.RubricCriterionID,
			&i.Level,
			&i.EvidenceText,
			&i.ModelConfidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCriterionEvidenceBySummaryID = `-- name: GetCriterionEvidenceBySummaryID :many
SELECT criterion_evidence_id, interview_summary_id, rubric_criterion_id, level, evidence_text, model_confidence, created_at
FROM app.criterion_evidence
WHERE interview_summary_id = $1::uuid
ORDER BY created_at ASC
`

func (q *Queries) GetCriterionEvidenceBySummaryID(ctx context.Context, interviewSummaryID pgtype.UUID) ([]AppCriterionEvidence, error) {
	rows, err := q.db.Query(ctx, getCriterionEvidenceBySummaryID, interviewSummaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppCriterionEvidence
	for rows.Next() {
		var i AppCriterionEvidence
		if err := rows.Scan(
			&i.CriterionEvidenceID,
			&i.InterviewSummaryID,
			&i.RubricCriterionID,
			&i.Level,
			&i.EvidenceText,
			&i.ModelConfidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
