// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: curriculum_descriptors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCurriculumDescriptor = `-- name: CreateCurriculumDescriptor :one
INSERT INTO app.curriculum_descriptors (
    code,
    subject,
    level_band,
    strand,
    substrand,
    description,
    elaborations,
    achievement_standard_excerpt,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::jsonb,
    $8,
    COALESCE($9::jsonb, '{}'::jsonb)
)
RETURNING curriculum_descriptor_id, code, subject, level_band, strand, substrand, description, elaborations, achievement_standard_excerpt, metadata, created_at, updated_at
`

type CreateCurriculumDescriptorParams struct {
	Code                       string      `db:"code" json:"code"`
	Subject                    string      `db:"subject" json:"subject"`
	LevelBand                  string      `db:"level_band" json:"levelBand"`
	Strand                     pgtype.Text `db:"strand" json:"strand"`
	Substrand                  pgtype.Text `db:"substrand" json:"substrand"`
	Description                string      `db:"description" json:"description"`
	Elaborations               []byte      `db:"elaborations" json:"elaborations"`
	AchievementStandardExcerpt pgtype.Text `db:"achievement_standard_excerpt" json:"achievementStandardExcerpt"`
	Metadata                   []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateCurriculumDescriptor(ctx context.Context, arg CreateCurriculumDescriptorParams) (AppCurriculumDescriptor, error) {
	row := q.db.QueryRow(ctx, createCurriculumDescriptor,
		arg.Code,
		arg.Subject,
		arg.LevelBand,
		arg.Strand,
		arg.Substrand,
		arg.Description,
		arg.Elaborations,
		arg.AchievementStandardExcerpt,
		arg.Metadata,
	)
	var i AppCurriculumDescriptor
	err := row.Scan(
		&i.CurriculumDescriptorID,
		&i.Code,
		&i.Subject,
		&i.LevelBand,
		&i.Strand,
		&i.Substrand,
		&i.Description,
		&i.Elaborations,
		&i.AchievementStandardExcerpt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurriculumDescriptorByCode = `-- name: GetCurriculumDescriptorByCode :one
SELECT curriculum_descriptor_id, code, subject, level_band, strand, substrand, description, elaborations, achievement_standard_excerpt, metadata, created_at, updated_at
FROM app.curriculum_descriptors
WHERE code = $1
`

func (q *Queries) GetCurriculumDescriptorByCode(ctx context.Context, code string) (AppCurriculumDescriptor, error) {
	row := q.db.QueryRow(ctx, getCurriculumDescriptorByCode, code)
	var i AppCurriculumDescriptor
	err := row.Scan(
		&i.CurriculumDescriptorID,
		&i.Code,
		&i.Subject,
		&i.LevelBand,
		&i.Strand,
		&i.Substrand,
		&i.Description,
		&i.Elaborations,
		&i.AchievementStandardExcerpt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurriculumDescriptorByID = `-- name: GetCurriculumDescriptorByID :one
SELECT curriculum_descriptor_id, code, subject, level_band, strand, substrand, description, elaborations, achievement_standard_excerpt, metadata, created_at, updated_at
FROM app.curriculum_descriptors
WHERE curriculum_descriptor_id = $1::uuid
`

func (q *Queries) GetCurriculumDescriptorByID(ctx context.Context, curriculumDescriptorID pgtype.UUID) (AppCurriculumDescriptor, error) {
	row := q.db.QueryRow(ctx, getCurriculumDescriptorByID, curriculumDescriptorID)
	var i AppCurriculumDescriptor
	err := row.Scan(
		&i.CurriculumDescriptorID,
		&i.Code,
		&i.Subject,
		&i.LevelBand,
		&i.Strand,
		&i.Substrand,
		&i.Description,
		&i.Elaborations,
		&i.AchievementStandardExcerpt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurriculumDescriptors = `-- name: ListCurriculumDescriptors :many
SELECT curriculum_descriptor_id, code, subject, level_band, strand, substrand, description, elaborations, achievement_standard_excerpt, metadata, created_at, updated_at
FROM app.curriculum_descriptors
WHERE ($1::text IS NULL OR subject = $1)
  AND ($2::text IS NULL OR level_band = $2)
ORDER BY code ASC
`

type ListCurriculumDescriptorsParams struct {
	Subject   string `db:"subject" json:"subject"`
	LevelBand string `db:"level_band" json:"levelBand"`
}

func (q *Queries) ListCurriculumDescriptors(ctx context.Context, arg ListCurriculumDescriptorsParams) ([]AppCurriculumDescriptor, error) {
	rows, err := q.db.Query(ctx, listCurriculumDescriptors, arg.Subject, arg.LevelBand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppCurriculumDescriptor
	for rows.Next() {
		var i AppCurriculumDescriptor
		if err := rows.Scan(
			&i.CurriculumDescriptorID,
			&i.Code,
			&i.Subject,
			&i.LevelBand,
			&i.Strand,
			&i.Substrand,
			&i.Description,
			&i.Elaborations,
			&i.AchievementStandardExcerpt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurriculumDescriptor = `-- name: UpdateCurriculumDescriptor :one
UPDATE app.curriculum_descriptors
SET code = $1,
    subject = $2,
    level_band = $3,
    strand = $4,
    substrand = $5,
    description = $6,
    elaborations = $7::jsonb,
    achievement_standard_excerpt = $8,
    metadata = $9::jsonb,
    updated_at = NOW()
WHERE curriculum_descriptor_id = $10::uuid
RETURNING curriculum_descriptor_id, code, subject, level_band, strand, substrand, description, elaborations, achievement_standard_excerpt, metadata, created_at, updated_at
`

type UpdateCurriculumDescriptorParams struct {
	Code                       string      `db:"code" json:"code"`
	Subject                    string      `db:"subject" json:"subject"`
	LevelBand                  string      `db:"level_band" json:"levelBand"`
	Strand                     pgtype.Text `db:"strand" json:"strand"`
	Substrand                  pgtype.Text `db:"substrand" json:"substrand"`
	Description                string      `db:"description" json:"description"`
	Elaborations               []byte      `db:"elaborations" json:"elaborations"`
	AchievementStandardExcerpt pgtype.Text `db:"achievement_standard_excerpt" json:"achievementStandardExcerpt"`
	Metadata                   []byte      `db:"metadata" json:"metadata"`
	CurriculumDescriptorID     pgtype.UUID `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
}

func (q *Queries) UpdateCurriculumDescriptor(ctx context.Context, arg UpdateCurriculumDescriptorParams) (AppCurriculumDescriptor, error) {
	row := q.db.QueryRow(ctx, updateCurriculumDescriptor,
		arg.Code,
		arg.Subject,
		arg.LevelBand,
		arg.Strand,
		arg.Substrand,
		arg.Description,
		arg.Elaborations,
		arg.AchievementStandardExcerpt,
		arg.Metadata,
		arg.CurriculumDescriptorID,
	)
	var i AppCurriculumDescriptor
	err := row.Scan(
		&i.CurriculumDescriptorID,
		&i.Code,
		&i.Subject,
		&i.LevelBand,
		&i.Strand,
		&i.Substrand,
		&i.Description,
		&i.Elaborations,
		&i.AchievementStandardExcerpt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
