// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterviewPlan = `-- name: CreateInterviewPlan :one
INSERT INTO app.interview_plans (rubric_id, title, instructions, config, status, curriculum_subject, curriculum_level_band)
VALUES (
    $1::uuid,
    $2,
    $3,
    COALESCE($4::jsonb, '{}'::jsonb),
    $5::app.interview_status,
    $6,
    $7
)
RETURNING interview_plan_id, rubric_id, title, instructions, config, status, curriculum_subject, curriculum_level_band, created_at, updated_at
`

type CreateInterviewPlanParams struct {
	RubricID            pgtype.UUID `db:"rubric_id" json:"rubricId"`
	Title               string      `db:"title" json:"title"`
	Instructions        pgtype.Text `db:"instructions" json:"instructions"`
	Config              []byte      `db:"config" json:"config"`
	Status              string      `db:"status" json:"status"`
	CurriculumSubject   pgtype.Text `db:"curriculum_subject" json:"curriculumSubject"`
	CurriculumLevelBand pgtype.Text `db:"curriculum_level_band" json:"curriculumLevelBand"`
}

func (q *Queries) CreateInterviewPlan(ctx context.Context, arg CreateInterviewPlanParams) (AppInterviewPlan, error) {
	row := q.db.QueryRow(ctx, createInterviewPlan,
		arg.RubricID,
		arg.Title,
		arg.Instructions,
		arg.Config,
		arg.Status,
		arg.CurriculumSubject,
		arg.CurriculumLevelBand,
	)
	var i AppInterviewPlan
	err := row.Scan(
		&i.InterviewPlanID,
		&i.RubricID,
		&i.Title,
		&i.Instructions,
		&i.Config,
		&i.Status,
		&i.CurriculumSubject,
		&i.CurriculumLevelBand,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInterviewPlanByID = `-- name: GetInterviewPlanByID :one
SELECT interview_plan_id, rubric_id, title, instructions, config, status, curriculum_subject, curriculum_level_band, created_at, updated_at
FROM app.interview_plans
WHERE interview_plan_id = $1::uuid
`

func (q *Queries) GetInterviewPlanByID(ctx context.Context, interviewPlanID pgtype.UUID) (AppInterviewPlan, error) {
	row := q.db.QueryRow(ctx, getInterviewPlanByID, interviewPlanID)
	var i AppInterviewPlan
	err := row.Scan(
		&i.InterviewPlanID,
		&i.RubricID,
		&i.Title,
		&i.Instructions,
		&i.Config,
		&i.Status,
		&i.CurriculumSubject,
		&i.CurriculumLevelBand,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlansByRubric = `-- name: ListPlansByRubric :many
SELECT interview_plan_id, rubric_id, title, instructions, config, status, curriculum_subject, curriculum_level_band, created_at, updated_at
FROM app.interview_plans
WHERE rubric_id = $1::uuid
ORDER BY created_at DESC
`

func (q *Queries) ListPlansByRubric(ctx context.Context, rubricID pgtype.UUID) ([]AppInterviewPlan, error) {
	rows, err := q.db.Query(ctx, listPlansByRubric, rubricID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppInterviewPlan
	for rows.Next() {
		var i AppInterviewPlan
		if err := rows.Scan(
			&i.InterviewPlanID,
			&i.RubricID,
			&i.Title,
			&i.Instructions,
			&i.Config,
			&i.Status,
			&i.CurriculumSubject,
			&i.CurriculumLevelBand,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewPlan = `-- name: UpdateInterviewPlan :one
UPDATE app.interview_plans
SET title = $1,
    instructions = $2,
    config = COALESCE($3::jsonb, config),
    status = $4::app.interview_status,
    curriculum_subject = $5,
    curriculum_level_band = $6,
    updated_at = NOW()
WHERE interview_plan_id = $7::uuid
RETURNING interview_plan_id, rubric_id, title, instructions, config, status, curriculum_subject, curriculum_level_band, created_at, updated_at
`

type UpdateInterviewPlanParams struct {
	Title               string      `db:"title" json:"title"`
	Instructions        pgtype.Text `db:"instructions" json:"instructions"`
	Config              []byte      `db:"config" json:"config"`
	Status              string      `db:"status" json:"status"`
	CurriculumSubject   pgtype.Text `db:"curriculum_subject" json:"curriculumSubject"`
	CurriculumLevelBand pgtype.Text `db:"curriculum_level_band" json:"curriculumLevelBand"`
	InterviewPlanID     pgtype.UUID `db:"interview_plan_id" json:"interviewPlanId"`
}

func (q *Queries) UpdateInterviewPlan(ctx context.Context, arg UpdateInterviewPlanParams) (AppInterviewPlan, error) {
	row := q.db.QueryRow(ctx, updateInterviewPlan,
		arg.Title,
		arg.Instructions,
		arg.Config,
		arg.Status,
		arg.CurriculumSubject,
		arg.CurriculumLevelBand,
		arg.InterviewPlanID,
	)
	var i AppInterviewPlan
	err := row.Scan(
		&i.InterviewPlanID,
		&i.RubricID,
		&i.Title,
		&i.Instructions,
		&i.Config,
		&i.Status,
		&i.CurriculumSubject,
		&i.CurriculumLevelBand,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInterviewPlanStatus = `-- name: UpdateInterviewPlanStatus :exec
UPDATE app.interview_plans
SET status = $1::app.interview_status,
    updated_at = NOW()
WHERE interview_plan_id = $2::uuid
`

type UpdateInterviewPlanStatusParams struct {
	Status          string      `db:"status" json:"status"`
	InterviewPlanID pgtype.UUID `db:"interview_plan_id" json:"interviewPlanId"`
}

func (q *Queries) UpdateInterviewPlanStatus(ctx context.Context, arg UpdateInterviewPlanStatusParams) error {
	_, err := q.db.Exec(ctx, updateInterviewPlanStatus, arg.Status, arg.InterviewPlanID)
	return err
}
