// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_question_misconception_tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllMisconceptionTagLinksForQuestion = `-- name: DeleteAllMisconceptionTagLinksForQuestion :exec
DELETE FROM app.interview_question_misconception_tags
WHERE interview_question_id = $1::uuid
`

func (q *Queries) DeleteAllMisconceptionTagLinksForQuestion(ctx context.Context, interviewQuestionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllMisconceptionTagLinksForQuestion, interviewQuestionID)
	return err
}

const getMisconceptionTagsByQuestionID = `-- name: GetMisconceptionTagsByQuestionID :many
SELECT mt.misconception_tag_id, mt.name, mt.display_name, mt.description, mt.concept_tag_id, mt.curriculum_descriptor_id, mt.created_at, mt.updated_at
FROM app.misconception_tags mt
INNER JOIN app.interview_question_misconception_tags iqmt
    ON mt.misconception_tag_id = iqmt.misconception_tag_id
WHERE iqmt.interview_question_id = $1::uuid
ORDER BY mt.name ASC
`

func (q *Queries) GetMisconceptionTagsByQuestionID(ctx context.Context, interviewQuestionID pgtype.UUID) ([]AppMisconceptionTag, error) {
	rows, err := q.db.Query(ctx, getMisconceptionTagsByQuestionID, interviewQuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMisconceptionTag
	for rows.Next() {
		var i AppMisconceptionTag
		if err := rows.Scan(
			&i.MisconceptionTagID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.ConceptTagID,
			&i.CurriculumDescriptorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsByMisconceptionTagID = `-- name: GetQuestionsByMisconceptionTagID :many
SELECT iq.interview_question_id, iq.interview_plan_id, iq.rubric_criterion_id, iq.prompt, iq.question_type, iq.order_index, iq.is_active, iq.follow_up_to_id, iq.follow_up_condition, iq.created_at, iq.updated_at
FROM app.interview_questions iq
INNER JOIN app.interview_question_misconception_tags iqmt
    ON iq.interview_question_id = iqmt.interview_question_id
WHERE iqmt.misconception_tag_id = $1::uuid
ORDER BY iq.order_index ASC
`

func (q *Queries) GetQuestionsByMisconceptionTagID(ctx context.Context, misconceptionTagID pgtype.UUID) ([]AppInterviewQuestion, error) {
	rows, err := q.db.Query(ctx, getQuestionsByMisconceptionTagID, misconceptionTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppInterviewQuestion
	for rows.Next() {
		var i AppInterviewQuestion
		if err := rows.Scan(
			&i.InterviewQuestionID,
			&i.InterviewPlanID,
			&i.RubricCriterionID,
			&i.Prompt,
			&i.QuestionType,
			&i.OrderIndex,
			&i.IsActive,
			&i.FollowUpToID,
			&i.FollowUpCondition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkQuestionToMisconceptionTag = `-- name: LinkQuestionToMisconceptionTag :one
INSERT INTO app.interview_question_misconception_tags (
    interview_question_id,
    misconception_tag_id
)
VALUES (
    $1::uuid,
    $2::uuid
)
RETURNING interview_question_id, misconception_tag_id
`

type LinkQuestionToMisconceptionTagParams struct {
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
	MisconceptionTagID  pgtype.UUID `db:"misconception_tag_id" json:"misconceptionTagId"`
}

func (q *Queries) LinkQuestionToMisconceptionTag(ctx context.Context, arg LinkQuestionToMisconceptionTagParams) (AppInterviewQuestionMisconceptionTag, error) {
	row := q.db.QueryRow(ctx, linkQuestionToMisconceptionTag, arg.InterviewQuestionID, arg.MisconceptionTagID)
	var i AppInterviewQuestionMisconceptionTag
	err := row.Scan(&i.InterviewQuestionID, &i.MisconceptionTagID)
	return i, err
}

const unlinkQuestionFromMisconceptionTag = `-- name: UnlinkQuestionFromMisconceptionTag :exec
DELETE FROM app.interview_question_misconception_tags
WHERE interview_question_id = $1::uuid
  AND misconception_tag_id = $2::uuid
`

type UnlinkQuestionFromMisconceptionTagParams struct {
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
	MisconceptionTagID  pgtype.UUID `db:"misconception_tag_id" json:"misconceptionTagId"`
}

func (q *Queries) UnlinkQuestionFromMisconceptionTag(ctx context.Context, arg UnlinkQuestionFromMisconceptionTagParams) error {
	_, err := q.db.Exec(ctx, unlinkQuestionFromMisconceptionTag, arg.InterviewQuestionID, arg.MisconceptionTagID)
	return err
}
