// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_question_branches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterviewQuestionBranch = `-- name: CreateInterviewQuestionBranch :one
INSERT INTO app.interview_question_branches (
    parent_question_id,
    response_category,
    misconception_tag_id,
    next_question_id,
    follow_up_prompt_override,
    terminate_interview,
    order_index
)
VALUES (
    $1::uuid,
    $2::app.response_category,
    $3::uuid,
    $4::uuid,
    $5,
    COALESCE($6, FALSE),
    $7
)
RETURNING interview_question_branch_id, parent_question_id, response_category, misconception_tag_id, next_question_id, follow_up_prompt_override, terminate_interview, order_index, created_at, updated_at
`

type CreateInterviewQuestionBranchParams struct {
	ParentQuestionID       pgtype.UUID `db:"parent_question_id" json:"parentQuestionId"`
	ResponseCategory       string      `db:"response_category" json:"responseCategory"`
	MisconceptionTagID     pgtype.UUID `db:"misconception_tag_id" json:"misconceptionTagId"`
	NextQuestionID         pgtype.UUID `db:"next_question_id" json:"nextQuestionId"`
	FollowUpPromptOverride pgtype.Text `db:"follow_up_prompt_override" json:"followUpPromptOverride"`
	TerminateInterview     interface{} `db:"terminate_interview" json:"terminateInterview"`
	OrderIndex             int32       `db:"order_index" json:"orderIndex"`
}

func (q *Queries) CreateInterviewQuestionBranch(ctx context.Context, arg CreateInterviewQuestionBranchParams) (AppInterviewQuestionBranch, error) {
	row := q.db.QueryRow(ctx, createInterviewQuestionBranch,
		arg.ParentQuestionID,
		arg.ResponseCategory,
		arg.MisconceptionTagID,
		arg.NextQuestionID,
		arg.FollowUpPromptOverride,
		arg.TerminateInterview,
		arg.OrderIndex,
	)
	var i AppInterviewQuestionBranch
	err := row.Scan(
		&i.InterviewQuestionBranchID,
		&i.ParentQuestionID,
		&i.ResponseCategory,
		&i.MisconceptionTagID,
		&i.NextQuestionID,
		&i.FollowUpPromptOverride,
		&i.TerminateInterview,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBranchesByParentQuestionID = `-- name: DeleteBranchesByParentQuestionID :exec
DELETE FROM app.interview_question_branches
WHERE parent_question_id = $1::uuid
`

func (q *Queries) DeleteBranchesByParentQuestionID(ctx context.Context, parentQuestionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBranchesByParentQuestionID, parentQuestionID)
	return err
}

const getBranchByCategory = `-- name: GetBranchByCategory :one
SELECT interview_question_branch_id, parent_question_id, response_category, misconception_tag_id, next_question_id, follow_up_prompt_override, terminate_interview, order_index, created_at, updated_at
FROM app.interview_question_branches
WHERE parent_question_id = $1::uuid
  AND response_category = $2::app.response_category
  AND (misconception_tag_id = $3::uuid OR ($3::uuid IS NULL AND misconception_tag_id IS NULL))
ORDER BY order_index ASC
LIMIT 1
`

type GetBranchByCategoryParams struct {
	ParentQuestionID   pgtype.UUID `db:"parent_question_id" json:"parentQuestionId"`
	ResponseCategory   string      `db:"response_category" json:"responseCategory"`
	MisconceptionTagID pgtype.UUID `db:"misconception_tag_id" json:"misconceptionTagId"`
}

func (q *Queries) GetBranchByCategory(ctx context.Context, arg GetBranchByCategoryParams) (AppInterviewQuestionBranch, error) {
	row := q.db.QueryRow(ctx, getBranchByCategory, arg.ParentQuestionID, arg.ResponseCategory, arg.MisconceptionTagID)
	var i AppInterviewQuestionBranch
	err := row.Scan(
		&i.InterviewQuestionBranchID,
		&i.ParentQuestionID,
		&i.ResponseCategory,
		&i.MisconceptionTagID,
		&i.NextQuestionID,
		&i.FollowUpPromptOverride,
		&i.TerminateInterview,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranchesByParentQuestionID = `-- name: GetBranchesByParentQuestionID :many
SELECT interview_question_branch_id, parent_question_id, response_category, misconception_tag_id, next_question_id, follow_up_prompt_override, terminate_interview, order_index, created_at, updated_at
FROM app.interview_question_branches
WHERE parent_question_id = $1::uuid
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) GetBranchesByParentQuestionID(ctx context.Context, parentQuestionID pgtype.UUID) ([]AppInterviewQuestionBranch, error) {
	rows, err := q.db.Query(ctx, getBranchesByParentQuestionID, parentQuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppInterviewQuestionBranch
	for rows.Next() {
		var i AppInterviewQuestionBranch
		if err := rows.Scan(
			&i.InterviewQuestionBranchID,
			&i.ParentQuestionID,
			&i.ResponseCategory,
			&i.MisconceptionTagID,
			&i.NextQuestionID,
			&i.FollowUpPromptOverride,
			&i.TerminateInterview,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewQuestionBranch = `-- name: UpdateInterviewQuestionBranch :one
UPDATE app.interview_question_branches
SET next_question_id = $1::uuid,
    follow_up_prompt_override = $2,
    terminate_interview = $3,
    order_index = $4,
    updated_at = NOW()
WHERE interview_question_branch_id = $5::uuid
RETURNING interview_question_branch_id, parent_question_id, response_category, misconception_tag_id, next_question_id, follow_up_prompt_override, terminate_interview, order_index, created_at, updated_at
`

type UpdateInterviewQuestionBranchParams struct {
	NextQuestionID            pgtype.UUID `db:"next_question_id" json:"nextQuestionId"`
	FollowUpPromptOverride    pgtype.Text `db:"follow_up_prompt_override" json:"followUpPromptOverride"`
	TerminateInterview        bool        `db:"terminate_interview" json:"terminateInterview"`
	OrderIndex                int32       `db:"order_index" json:"orderIndex"`
	InterviewQuestionBranchID pgtype.UUID `db:"interview_question_branch_id" json:"interviewQuestionBranchId"`
}

func (q *Queries) UpdateInterviewQuestionBranch(ctx context.Context, arg UpdateInterviewQuestionBranchParams) (AppInterviewQuestionBranch, error) {
	row := q.db.QueryRow(ctx, updateInterviewQuestionBranch,
		arg.NextQuestionID,
		arg.FollowUpPromptOverride,
		arg.TerminateInterview,
		arg.OrderIndex,
		arg.InterviewQuestionBranchID,
	)
	var i AppInterviewQuestionBranch
	err := row.Scan(
		&i.InterviewQuestionBranchID,
		&i.ParentQuestionID,
		&i.ResponseCategory,
		&i.MisconceptionTagID,
		&i.NextQuestionID,
		&i.FollowUpPromptOverride,
		&i.TerminateInterview,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
