// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterview = `-- name: CreateInterview :one
INSERT INTO app.interviews (
    interview_plan_id,
    teacher_id,
    student_id,
    simulated,
    student_name,
    status,
    submission_id
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6::app.interview_status,
    $7::uuid
)
RETURNING interview_id, interview_plan_id, teacher_id, student_id, simulated, student_name, status, started_at, completed_at, submission_id
`

type CreateInterviewParams struct {
	InterviewPlanID pgtype.UUID `db:"interview_plan_id" json:"interviewPlanId"`
	TeacherID       pgtype.UUID `db:"teacher_id" json:"teacherId"`
	StudentID       pgtype.UUID `db:"student_id" json:"studentId"`
	Simulated       bool        `db:"simulated" json:"simulated"`
	StudentName     pgtype.Text `db:"student_name" json:"studentName"`
	Status          string      `db:"status" json:"status"`
	SubmissionID    pgtype.UUID `db:"submission_id" json:"submissionId"`
}

func (q *Queries) CreateInterview(ctx context.Context, arg CreateInterviewParams) (AppInterview, error) {
	row := q.db.QueryRow(ctx, createInterview,
		arg.InterviewPlanID,
		arg.TeacherID,
		arg.StudentID,
		arg.Simulated,
		arg.StudentName,
		arg.Status,
		arg.SubmissionID,
	)
	var i AppInterview
	err := row.Scan(
		&i.InterviewID,
		&i.InterviewPlanID,
		&i.TeacherID,
		&i.StudentID,
		&i.Simulated,
		&i.StudentName,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.SubmissionID,
	)
	return i, err
}

const getInterviewByID = `-- name: GetInterviewByID :one
SELECT interview_id, interview_plan_id, teacher_id, student_id, simulated, student_name, status, started_at, completed_at, submission_id
FROM app.interviews
WHERE interview_id = $1::uuid
`

func (q *Queries) GetInterviewByID(ctx context.Context, interviewID pgtype.UUID) (AppInterview, error) {
	row := q.db.QueryRow(ctx, getInterviewByID, interviewID)
	var i AppInterview
	err := row.Scan(
		&i.InterviewID,
		&i.InterviewPlanID,
		&i.TeacherID,
		&i.StudentID,
		&i.Simulated,
		&i.StudentName,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.SubmissionID,
	)
	return i, err
}

const getInterviewBySubmissionID = `-- name: GetInterviewBySubmissionID :one
SELECT interview_id, interview_plan_id, teacher_id, student_id, simulated, student_name, status, started_at, completed_at, submission_id
FROM app.interviews
WHERE submission_id = $1::uuid
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetInterviewBySubmissionID(ctx context.Context, submissionID pgtype.UUID) (AppInterview, error) {
	row := q.db.QueryRow(ctx, getInterviewBySubmissionID, submissionID)
	var i AppInterview
	err := row.Scan(
		&i.InterviewID,
		&i.InterviewPlanID,
		&i.TeacherID,
		&i.StudentID,
		&i.Simulated,
		&i.StudentName,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.SubmissionID,
	)
	return i, err
}

const linkInterviewToSubmission = `-- name: LinkInterviewToSubmission :exec
UPDATE app.interviews
SET submission_id = $1::uuid
WHERE interview_id = $2::uuid
`

type LinkInterviewToSubmissionParams struct {
	SubmissionID pgtype.UUID `db:"submission_id" json:"submissionId"`
	InterviewID  pgtype.UUID `db:"interview_id" json:"interviewId"`
}

func (q *Queries) LinkInterviewToSubmission(ctx context.Context, arg LinkInterviewToSubmissionParams) error {
	_, err := q.db.Exec(ctx, linkInterviewToSubmission, arg.SubmissionID, arg.InterviewID)
	return err
}

const listInterviewsByPlan = `-- name: ListInterviewsByPlan :many
SELECT interview_id, interview_plan_id, teacher_id, student_id, simulated, student_name, status, started_at, completed_at, submission_id
FROM app.interviews
WHERE interview_plan_id = $1::uuid
ORDER BY started_at DESC
`

func (q *Queries) ListInterviewsByPlan(ctx context.Context, interviewPlanID pgtype.UUID) ([]AppInterview, error) {
	rows, err := q.db.Query(ctx, listInterviewsByPlan, interviewPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppInterview
	for rows.Next() {
		var i AppInterview
		if err := rows.Scan(
			&i.InterviewID,
			&i.InterviewPlanID,
			&i.TeacherID,
			&i.StudentID,
			&i.Simulated,
			&i.StudentName,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.SubmissionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewStatus = `-- name: UpdateInterviewStatus :exec
UPDATE app.interviews
SET status = $1::app.interview_status,
    completed_at = CASE
        WHEN $1::app.interview_status = 'completed' THEN NOW()
        ELSE completed_at
    END
WHERE interview_id = $2::uuid
`

type UpdateInterviewStatusParams struct {
	Status      string      `db:"status" json:"status"`
	InterviewID pgtype.UUID `db:"interview_id" json:"interviewId"`
}

func (q *Queries) UpdateInterviewStatus(ctx context.Context, arg UpdateInterviewStatusParams) error {
	_, err := q.db.Exec(ctx, updateInterviewStatus, arg.Status, arg.InterviewID)
	return err
}
