// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterviewMessage = `-- name: CreateInterviewMessage :one
INSERT INTO app.interview_messages (
    interview_id,
    sender,
    interview_question_id,
    content
)
VALUES (
    $1::uuid,
    $2::app.message_sender,
    $3::uuid,
    $4
)
RETURNING interview_message_id, interview_id, sender, interview_question_id, content, created_at
`

type CreateInterviewMessageParams struct {
	InterviewID         pgtype.UUID `db:"interview_id" json:"interviewId"`
	Sender              string      `db:"sender" json:"sender"`
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
	Content             string      `db:"content" json:"content"`
}

func (q *Queries) CreateInterviewMessage(ctx context.Context, arg CreateInterviewMessageParams) (AppInterviewMessage, error) {
	row := q.db.QueryRow(ctx, createInterviewMessage,
		arg.InterviewID,
		arg.Sender,
		arg.InterviewQuestionID,
		arg.Content,
	)
	var i AppInterviewMessage
	err := row.Scan(
		&i.InterviewMessageID,
		&i.InterviewID,
		&i.Sender,
		&i.InterviewQuestionID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByInterview = `-- name: ListMessagesByInterview :many
SELECT interview_message_id, interview_id, sender, interview_question_id, content, created_at
FROM app.interview_messages
WHERE interview_id = $1::uuid
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByInterview(ctx context.Context, interviewID pgtype.UUID) ([]AppInterviewMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesByInterview, interviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppInterviewMessage
	for rows.Next() {
		var i AppInterviewMessage
		if err := rows.Scan(
			&i.InterviewMessageID,
			&i.InterviewID,
			&i.Sender,
			&i.InterviewQuestionID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
