// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_questions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterviewQuestion = `-- name: CreateInterviewQuestion :one
INSERT INTO app.interview_questions (
    interview_plan_id,
    rubric_criterion_id,
    prompt,
    question_type,
    order_index,
    is_active,
    follow_up_to_id,
    follow_up_condition
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3,
    $4,
    $5,
    COALESCE($6, TRUE),
    $7::uuid,
    $8
)
RETURNING interview_question_id, interview_plan_id, rubric_criterion_id, prompt, question_type, order_index, is_active, follow_up_to_id, follow_up_condition, created_at, updated_at
`

type CreateInterviewQuestionParams struct {
	InterviewPlanID   pgtype.UUID `db:"interview_plan_id" json:"interviewPlanId"`
	RubricCriterionID pgtype.UUID `db:"rubric_criterion_id" json:"rubricCriterionId"`
	Prompt            string      `db:"prompt" json:"prompt"`
	QuestionType      string      `db:"question_type" json:"questionType"`
	OrderIndex        int32       `db:"order_index" json:"orderIndex"`
	IsActive          interface{} `db:"is_active" json:"isActive"`
	FollowUpToID      pgtype.UUID `db:"follow_up_to_id" json:"followUpToId"`
	FollowUpCondition pgtype.Text `db:"follow_up_condition" json:"followUpCondition"`
}

func (q *Queries) CreateInterviewQuestion(ctx context.Context, arg CreateInterviewQuestionParams) (AppInterviewQuestion, error) {
	row := q.db.QueryRow(ctx, createInterviewQuestion,
		arg.InterviewPlanID,
		arg.RubricCriterionID,
		arg.Prompt,
		arg.QuestionType,
		arg.OrderIndex,
		arg.IsActive,
		arg.FollowUpToID,
		arg.FollowUpCondition,
	)
	var i AppInterviewQuestion
	err := row.Scan(
		&i.InterviewQuestionID,
		&i.InterviewPlanID,
		&i.RubricCriterionID,
		&i.Prompt,
		&i.QuestionType,
		&i.OrderIndex,
		&i.IsActive,
		&i.FollowUpToID,
		&i.FollowUpCondition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestionsByPlan = `-- name: DeleteQuestionsByPlan :exec
DELETE FROM app.interview_questions
WHERE interview_plan_id = $1::uuid
`

func (q *Queries) DeleteQuestionsByPlan(ctx context.Context, interviewPlanID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestionsByPlan, interviewPlanID)
	return err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT interview_question_id, interview_plan_id, rubric_criterion_id, prompt, question_type, order_index, is_active, follow_up_to_id, follow_up_condition, created_at, updated_at
FROM app.interview_questions
WHERE interview_question_id = $1::uuid
`

func (q *Queries) GetQuestionByID(ctx context.Context, interviewQuestionID pgtype.UUID) (AppInterviewQuestion, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, interviewQuestionID)
	var i AppInterviewQuestion
	err := row.Scan(
		&i.InterviewQuestionID,
		&i.InterviewPlanID,
		&i.RubricCriterionID,
		&i.Prompt,
		&i.QuestionType,
		&i.OrderIndex,
		&i.IsActive,
		&i.FollowUpToID,
		&i.FollowUpCondition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuestionsByPlan = `-- name: ListQuestionsByPlan :many
SELECT interview_question_id, interview_plan_id, rubric_criterion_id, prompt, question_type, order_index, is_active, follow_up_to_id, follow_up_condition, created_at, updated_at
FROM app.interview_questions
WHERE interview_plan_id = $1::uuid
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListQuestionsByPlan(ctx context.Context, interviewPlanID pgtype.UUID) ([]AppInterviewQuestion, error) {
	rows, err := q.db.Query(ctx, listQuestionsByPlan, interviewPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppInterviewQuestion
	for rows.Next() {
		var i AppInterviewQuestion
		if err := rows.Scan(
			&i.InterviewQuestionID,
			&i.InterviewPlanID,
			&i.RubricCriterionID,
			&i.Prompt,
			&i.QuestionType,
			&i.OrderIndex,
			&i.IsActive,
			&i.FollowUpToID,
			&i.FollowUpCondition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewQuestion = `-- name: UpdateInterviewQuestion :one
UPDATE app.interview_questions
SET prompt = $1,
    question_type = $2,
    order_index = $3,
    is_active = $4,
    rubric_criterion_id = $5::uuid,
    follow_up_to_id = $6::uuid,
    follow_up_condition = $7,
    updated_at = NOW()
WHERE interview_question_id = $8::uuid
RETURNING interview_question_id, interview_plan_id, rubric_criterion_id, prompt, question_type, order_index, is_active, follow_up_to_id, follow_up_condition, created_at, updated_at
`

type UpdateInterviewQuestionParams struct {
	Prompt              string      `db:"prompt" json:"prompt"`
	QuestionType        string      `db:"question_type" json:"questionType"`
	OrderIndex          int32       `db:"order_index" json:"orderIndex"`
	IsActive            bool        `db:"is_active" json:"isActive"`
	RubricCriterionID   pgtype.UUID `db:"rubric_criterion_id" json:"rubricCriterionId"`
	FollowUpToID        pgtype.UUID `db:"follow_up_to_id" json:"followUpToId"`
	FollowUpCondition   pgtype.Text `db:"follow_up_condition" json:"followUpCondition"`
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
}

func (q *Queries) UpdateInterviewQuestion(ctx context.Context, arg UpdateInterviewQuestionParams) (AppInterviewQuestion, error) {
	row := q.db.QueryRow(ctx, updateInterviewQuestion,
		arg.Prompt,
		arg.QuestionType,
		arg.OrderIndex,
		arg.IsActive,
		arg.RubricCriterionID,
		arg.FollowUpToID,
		arg.FollowUpCondition,
		arg.InterviewQuestionID,
	)
	var i AppInterviewQuestion
	err := row.Scan(
		&i.InterviewQuestionID,
		&i.InterviewPlanID,
		&i.RubricCriterionID,
		&i.Prompt,
		&i.QuestionType,
		&i.OrderIndex,
		&i.IsActive,
		&i.FollowUpToID,
		&i.FollowUpCondition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
