// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_question_concept_tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllConceptTagLinksForQuestion = `-- name: DeleteAllConceptTagLinksForQuestion :exec
DELETE FROM app.interview_question_concept_tags
WHERE interview_question_id = $1::uuid
`

func (q *Queries) DeleteAllConceptTagLinksForQuestion(ctx context.Context, interviewQuestionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllConceptTagLinksForQuestion, interviewQuestionID)
	return err
}

const getConceptTagsByQuestionID = `-- name: GetConceptTagsByQuestionID :many
SELECT ct.concept_tag_id, ct.name, ct.display_name, ct.description, ct.curriculum_descriptor_id, ct.created_at, ct.updated_at
FROM app.concept_tags ct
INNER JOIN app.interview_question_concept_tags iqct
    ON ct.concept_tag_id = iqct.concept_tag_id
WHERE iqct.interview_question_id = $1::uuid
ORDER BY ct.name ASC
`

func (q *Queries) GetConceptTagsByQuestionID(ctx context.Context, interviewQuestionID pgtype.UUID) ([]AppConceptTag, error) {
	rows, err := q.db.Query(ctx, getConceptTagsByQuestionID, interviewQuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppConceptTag
	for rows.Next() {
		var i AppConceptTag
		if err := rows.Scan(
			&i.ConceptTagID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.CurriculumDescriptorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsByConceptTagID = `-- name: GetQuestionsByConceptTagID :many
SELECT iq.interview_question_id, iq.interview_plan_id, iq.rubric_criterion_id, iq.prompt, iq.question_type, iq.order_index, iq.is_active, iq.follow_up_to_id, iq.follow_up_condition, iq.created_at, iq.updated_at
FROM app.interview_questions iq
INNER JOIN app.interview_question_concept_tags iqct
    ON iq.interview_question_id = iqct.interview_question_id
WHERE iqct.concept_tag_id = $1::uuid
ORDER BY iq.order_index ASC
`

func (q *Queries) GetQuestionsByConceptTagID(ctx context.Context, conceptTagID pgtype.UUID) ([]AppInterviewQuestion, error) {
	rows, err := q.db.Query(ctx, getQuestionsByConceptTagID, conceptTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppInterviewQuestion
	for rows.Next() {
		var i AppInterviewQuestion
		if err := rows.Scan(
			&i.InterviewQuestionID,
			&i.InterviewPlanID,
			&i.RubricCriterionID,
			&i.Prompt,
			&i.QuestionType,
			&i.OrderIndex,
			&i.IsActive,
			&i.FollowUpToID,
			&i.FollowUpCondition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkQuestionToConceptTag = `-- name: LinkQuestionToConceptTag :one
INSERT INTO app.interview_question_concept_tags (
    interview_question_id,
    concept_tag_id
)
VALUES (
    $1::uuid,
    $2::uuid
)
RETURNING interview_question_id, concept_tag_id
`

type LinkQuestionToConceptTagParams struct {
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
	ConceptTagID        pgtype.UUID `db:"concept_tag_id" json:"conceptTagId"`
}

func (q *Queries) LinkQuestionToConceptTag(ctx context.Context, arg LinkQuestionToConceptTagParams) (AppInterviewQuestionConceptTag, error) {
	row := q.db.QueryRow(ctx, linkQuestionToConceptTag, arg.InterviewQuestionID, arg.ConceptTagID)
	var i AppInterviewQuestionConceptTag
	err := row.Scan(&i.InterviewQuestionID, &i.ConceptTagID)
	return i, err
}

const unlinkQuestionFromConceptTag = `-- name: UnlinkQuestionFromConceptTag :exec
DELETE FROM app.interview_question_concept_tags
WHERE interview_question_id = $1::uuid
  AND concept_tag_id = $2::uuid
`

type UnlinkQuestionFromConceptTagParams struct {
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
	ConceptTagID        pgtype.UUID `db:"concept_tag_id" json:"conceptTagId"`
}

func (q *Queries) UnlinkQuestionFromConceptTag(ctx context.Context, arg UnlinkQuestionFromConceptTagParams) error {
	_, err := q.db.Exec(ctx, unlinkQuestionFromConceptTag, arg.InterviewQuestionID, arg.ConceptTagID)
	return err
}
