// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interview_plan_curriculum_descriptors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllLinksForPlan = `-- name: DeleteAllLinksForPlan :exec
DELETE FROM app.interview_plan_curriculum_descriptors
WHERE interview_plan_id = $1::uuid
`

func (q *Queries) DeleteAllLinksForPlan(ctx context.Context, interviewPlanID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllLinksForPlan, interviewPlanID)
	return err
}

const getCurriculumDescriptorsByPlanID = `-- name: GetCurriculumDescriptorsByPlanID :many
SELECT cd.curriculum_descriptor_id, cd.code, cd.subject, cd.level_band, cd.strand, cd.substrand, cd.description, cd.elaborations, cd.achievement_standard_excerpt, cd.metadata, cd.created_at, cd.updated_at
FROM app.curriculum_descriptors cd
INNER JOIN app.interview_plan_curriculum_descriptors ipcd
    ON cd.curriculum_descriptor_id = ipcd.curriculum_descriptor_id
WHERE ipcd.interview_plan_id = $1::uuid
ORDER BY ipcd.primary_alignment DESC, cd.code ASC
`

func (q *Queries) GetCurriculumDescriptorsByPlanID(ctx context.Context, interviewPlanID pgtype.UUID) ([]AppCurriculumDescriptor, error) {
	rows, err := q.db.Query(ctx, getCurriculumDescriptorsByPlanID, interviewPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppCurriculumDescriptor
	for rows.Next() {
		var i AppCurriculumDescriptor
		if err := rows.Scan(
			&i.CurriculumDescriptorID,
			&i.Code,
			&i.Subject,
			&i.LevelBand,
			&i.Strand,
			&i.Substrand,
			&i.Description,
			&i.Elaborations,
			&i.AchievementStandardExcerpt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInterviewPlansByCurriculumDescriptorID = `-- name: GetInterviewPlansByCurriculumDescriptorID :many
SELECT ip.interview_plan_id, ip.rubric_id, ip.title, ip.instructions, ip.config, ip.status, ip.curriculum_subject, ip.curriculum_level_band, ip.created_at, ip.updated_at
FROM app.interview_plans ip
INNER JOIN app.interview_plan_curriculum_descriptors ipcd
    ON ip.interview_plan_id = ipcd.interview_plan_id
WHERE ipcd.curriculum_descriptor_id = $1::uuid
ORDER BY ip.created_at DESC
`

func (q *Queries) GetInterviewPlansByCurriculumDescriptorID(ctx context.Context, curriculumDescriptorID pgtype.UUID) ([]AppInterviewPlan, error) {
	rows, err := q.db.Query(ctx, getInterviewPlansByCurriculumDescriptorID, curriculumDescriptorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppInterviewPlan
	for rows.Next() {
		var i AppInterviewPlan
		if err := rows.Scan(
			&i.InterviewPlanID,
			&i.RubricID,
			&i.Title,
			&i.Instructions,
			&i.Config,
			&i.Status,
			&i.CurriculumSubject,
			&i.CurriculumLevelBand,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkInterviewPlanToCurriculumDescriptor = `-- name: LinkInterviewPlanToCurriculumDescriptor :one
INSERT INTO app.interview_plan_curriculum_descriptors (
    interview_plan_id,
    curriculum_descriptor_id,
    primary_alignment
)
VALUES (
    $1::uuid,
    $2::uuid,
    COALESCE($3, FALSE)
)
RETURNING interview_plan_id, curriculum_descriptor_id, primary_alignment, created_at
`

type LinkInterviewPlanToCurriculumDescriptorParams struct {
	InterviewPlanID        pgtype.UUID `db:"interview_plan_id" json:"interviewPlanId"`
	CurriculumDescriptorID pgtype.UUID `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	PrimaryAlignment       interface{} `db:"primary_alignment" json:"primaryAlignment"`
}

func (q *Queries) LinkInterviewPlanToCurriculumDescriptor(ctx context.Context, arg LinkInterviewPlanToCurriculumDescriptorParams) (AppInterviewPlanCurriculumDescriptor, error) {
	row := q.db.QueryRow(ctx, linkInterviewPlanToCurriculumDescriptor, arg.InterviewPlanID, arg.CurriculumDescriptorID, arg.PrimaryAlignment)
	var i AppInterviewPlanCurriculumDescriptor
	err := row.Scan(
		&i.InterviewPlanID,
		&i.CurriculumDescriptorID,
		&i.PrimaryAlignment,
		&i.CreatedAt,
	)
	return i, err
}

const unlinkInterviewPlanFromCurriculumDescriptor = `-- name: UnlinkInterviewPlanFromCurriculumDescriptor :exec
DELETE FROM app.interview_plan_curriculum_descriptors
WHERE interview_plan_id = $1::uuid
  AND curriculum_descriptor_id = $2::uuid
`

type UnlinkInterviewPlanFromCurriculumDescriptorParams struct {
	InterviewPlanID        pgtype.UUID `db:"interview_plan_id" json:"interviewPlanId"`
	CurriculumDescriptorID pgtype.UUID `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
}

func (q *Queries) UnlinkInterviewPlanFromCurriculumDescriptor(ctx context.Context, arg UnlinkInterviewPlanFromCurriculumDescriptorParams) error {
	_, err := q.db.Exec(ctx, unlinkInterviewPlanFromCurriculumDescriptor, arg.InterviewPlanID, arg.CurriculumDescriptorID)
	return err
}
