// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: misconception_tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMisconceptionTag = `-- name: CreateMisconceptionTag :one
INSERT INTO app.misconception_tags (
    name,
    display_name,
    description,
    concept_tag_id,
    curriculum_descriptor_id
)
VALUES (
    $1,
    $2,
    $3,
    $4::uuid,
    $5::uuid
)
RETURNING misconception_tag_id, name, display_name, description, concept_tag_id, curriculum_descriptor_id, created_at, updated_at
`

type CreateMisconceptionTagParams struct {
	Name                   string      `db:"name" json:"name"`
	DisplayName            pgtype.Text `db:"display_name" json:"displayName"`
	Description            pgtype.Text `db:"description" json:"description"`
	ConceptTagID           pgtype.UUID `db:"concept_tag_id" json:"conceptTagId"`
	CurriculumDescriptorID pgtype.UUID `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
}

func (q *Queries) CreateMisconceptionTag(ctx context.Context, arg CreateMisconceptionTagParams) (AppMisconceptionTag, error) {
	row := q.db.QueryRow(ctx, createMisconceptionTag,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.ConceptTagID,
		arg.CurriculumDescriptorID,
	)
	var i AppMisconceptionTag
	err := row.Scan(
		&i.MisconceptionTagID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ConceptTagID,
		&i.CurriculumDescriptorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMisconceptionTagByID = `-- name: GetMisconceptionTagByID :one
SELECT misconception_tag_id, name, display_name, description, concept_tag_id, curriculum_descriptor_id, created_at, updated_at
FROM app.misconception_tags
WHERE misconception_tag_id = $1::uuid
`

func (q *Queries) GetMisconceptionTagByID(ctx context.Context, misconceptionTagID pgtype.UUID) (AppMisconceptionTag, error) {
	row := q.db.QueryRow(ctx, getMisconceptionTagByID, misconceptionTagID)
	var i AppMisconceptionTag
	err := row.Scan(
		&i.MisconceptionTagID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ConceptTagID,
		&i.CurriculumDescriptorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMisconceptionTagByName = `-- name: GetMisconceptionTagByName :one
SELECT misconception_tag_id, name, display_name, description, concept_tag_id, curriculum_descriptor_id, created_at, updated_at
FROM app.misconception_tags
WHERE curriculum_descriptor_id = $1::uuid
  AND name = $2
`

type GetMisconceptionTagByNameParams struct {
	CurriculumDescriptorID pgtype.UUID `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	Name                   string      `db:"name" json:"name"`
}

func (q *Queries) GetMisconceptionTagByName(ctx context.Context, arg GetMisconceptionTagByNameParams) (AppMisconceptionTag, error) {
	row := q.db.QueryRow(ctx, getMisconceptionTagByName, arg.CurriculumDescriptorID, arg.Name)
	var i AppMisconceptionTag
	err := row.Scan(
		&i.MisconceptionTagID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ConceptTagID,
		&i.CurriculumDescriptorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMisconceptionTagsByConcept = `-- name: ListMisconceptionTagsByConcept :many
SELECT misconception_tag_id, name, display_name, description, concept_tag_id, curriculum_descriptor_id, created_at, updated_at
FROM app.misconception_tags
WHERE concept_tag_id = $1::uuid
ORDER BY name ASC
`

func (q *Queries) ListMisconceptionTagsByConcept(ctx context.Context, conceptTagID pgtype.UUID) ([]AppMisconceptionTag, error) {
	rows, err := q.db.Query(ctx, listMisconceptionTagsByConcept, conceptTagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMisconceptionTag
	for rows.Next() {
		var i AppMisconceptionTag
		if err := rows.Scan(
			&i.MisconceptionTagID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.ConceptTagID,
			&i.CurriculumDescriptorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMisconceptionTagsByDescriptor = `-- name: ListMisconceptionTagsByDescriptor :many
SELECT misconception_tag_id, name, display_name, description, concept_tag_id, curriculum_descriptor_id, created_at, updated_at
FROM app.misconception_tags
WHERE curriculum_descriptor_id = $1::uuid
ORDER BY name ASC
`

func (q *Queries) ListMisconceptionTagsByDescriptor(ctx context.Context, curriculumDescriptorID pgtype.UUID) ([]AppMisconceptionTag, error) {
	rows, err := q.db.Query(ctx, listMisconceptionTagsByDescriptor, curriculumDescriptorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMisconceptionTag
	for rows.Next() {
		var i AppMisconceptionTag
		if err := rows.Scan(
			&i.MisconceptionTagID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.ConceptTagID,
			&i.CurriculumDescriptorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMisconceptionTag = `-- name: UpdateMisconceptionTag :one
UPDATE app.misconception_tags
SET display_name = $1,
    description = $2,
    updated_at = NOW()
WHERE misconception_tag_id = $3::uuid
RETURNING misconception_tag_id, name, display_name, description, concept_tag_id, curriculum_descriptor_id, created_at, updated_at
`

type UpdateMisconceptionTagParams struct {
	DisplayName        pgtype.Text `db:"display_name" json:"displayName"`
	Description        pgtype.Text `db:"description" json:"description"`
	MisconceptionTagID pgtype.UUID `db:"misconception_tag_id" json:"misconceptionTagId"`
}

func (q *Queries) UpdateMisconceptionTag(ctx context.Context, arg UpdateMisconceptionTagParams) (AppMisconceptionTag, error) {
	row := q.db.QueryRow(ctx, updateMisconceptionTag, arg.DisplayName, arg.Description, arg.MisconceptionTagID)
	var i AppMisconceptionTag
	err := row.Scan(
		&i.MisconceptionTagID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.ConceptTagID,
		&i.CurriculumDescriptorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
