// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppAlignmentLevel string

const (
	AppAlignmentLevelStrong  AppAlignmentLevel = "strong"
	AppAlignmentLevelPartial AppAlignmentLevel = "partial"
	AppAlignmentLevelWeak    AppAlignmentLevel = "weak"
)

func (e *AppAlignmentLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppAlignmentLevel(s)
	case string:
		*e = AppAlignmentLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for AppAlignmentLevel: %T", src)
	}
	return nil
}

type NullAppAlignmentLevel struct {
	AppAlignmentLevel AppAlignmentLevel `json:"appAlignmentLevel"`
	Valid             bool              `json:"valid"` // Valid is true if AppAlignmentLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppAlignmentLevel) Scan(value interface{}) error {
	if value == nil {
		ns.AppAlignmentLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppAlignmentLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppAlignmentLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppAlignmentLevel), nil
}

type AppArtifactType string

const (
	AppArtifactTypeMainText        AppArtifactType = "main_text"
	AppArtifactTypeDraftCheckpoint AppArtifactType = "draft_checkpoint"
	AppArtifactTypeRevisionNote    AppArtifactType = "revision_note"
	AppArtifactTypeCitationSource  AppArtifactType = "citation_source"
	AppArtifactTypeFileRef         AppArtifactType = "file_ref"
)

func (e *AppArtifactType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppArtifactType(s)
	case string:
		*e = AppArtifactType(s)
	default:
		return fmt.Errorf("unsupported scan type for AppArtifactType: %T", src)
	}
	return nil
}

type NullAppArtifactType struct {
	AppArtifactType AppArtifactType `json:"appArtifactType"`
	Valid           bool            `json:"valid"` // Valid is true if AppArtifactType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppArtifactType) Scan(value interface{}) error {
	if value == nil {
		ns.AppArtifactType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppArtifactType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppArtifactType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppArtifactType), nil
}

type AppAuthorshipRecommendation string

const (
	AppAuthorshipRecommendationNoAction             AppAuthorshipRecommendation = "no_action"
	AppAuthorshipRecommendationReflectionSuggested  AppAuthorshipRecommendation = "reflection_suggested"
	AppAuthorshipRecommendationMicroVivaRecommended AppAuthorshipRecommendation = "micro_viva_recommended"
)

func (e *AppAuthorshipRecommendation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppAuthorshipRecommendation(s)
	case string:
		*e = AppAuthorshipRecommendation(s)
	default:
		return fmt.Errorf("unsupported scan type for AppAuthorshipRecommendation: %T", src)
	}
	return nil
}

type NullAppAuthorshipRecommendation struct {
	AppAuthorshipRecommendation AppAuthorshipRecommendation `json:"appAuthorshipRecommendation"`
	Valid                       bool                        `json:"valid"` // Valid is true if AppAuthorshipRecommendation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppAuthorshipRecommendation) Scan(value interface{}) error {
	if value == nil {
		ns.AppAuthorshipRecommendation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppAuthorshipRecommendation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppAuthorshipRecommendation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppAuthorshipRecommendation), nil
}

type AppDiscrepancyLevel string

const (
	AppDiscrepancyLevelLow      AppDiscrepancyLevel = "low"
	AppDiscrepancyLevelModerate AppDiscrepancyLevel = "moderate"
	AppDiscrepancyLevelHigh     AppDiscrepancyLevel = "high"
)

func (e *AppDiscrepancyLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppDiscrepancyLevel(s)
	case string:
		*e = AppDiscrepancyLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for AppDiscrepancyLevel: %T", src)
	}
	return nil
}

type NullAppDiscrepancyLevel struct {
	AppDiscrepancyLevel AppDiscrepancyLevel `json:"appDiscrepancyLevel"`
	Valid               bool                `json:"valid"` // Valid is true if AppDiscrepancyLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppDiscrepancyLevel) Scan(value interface{}) error {
	if value == nil {
		ns.AppDiscrepancyLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppDiscrepancyLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppDiscrepancyLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppDiscrepancyLevel), nil
}

type AppInterviewStatus string

const (
	AppInterviewStatusDraft      AppInterviewStatus = "draft"
	AppInterviewStatusInProgress AppInterviewStatus = "in_progress"
	AppInterviewStatusCompleted  AppInterviewStatus = "completed"
)

func (e *AppInterviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppInterviewStatus(s)
	case string:
		*e = AppInterviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppInterviewStatus: %T", src)
	}
	return nil
}

type NullAppInterviewStatus struct {
	AppInterviewStatus AppInterviewStatus `json:"appInterviewStatus"`
	Valid              bool               `json:"valid"` // Valid is true if AppInterviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppInterviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppInterviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppInterviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppInterviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppInterviewStatus), nil
}

type AppMessageSender string

const (
	AppMessageSenderAi   AppMessageSender = "ai"
	AppMessageSenderUser AppMessageSender = "user"
)

func (e *AppMessageSender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppMessageSender(s)
	case string:
		*e = AppMessageSender(s)
	default:
		return fmt.Errorf("unsupported scan type for AppMessageSender: %T", src)
	}
	return nil
}

type NullAppMessageSender struct {
	AppMessageSender AppMessageSender `json:"appMessageSender"`
	Valid            bool             `json:"valid"` // Valid is true if AppMessageSender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppMessageSender) Scan(value interface{}) error {
	if value == nil {
		ns.AppMessageSender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppMessageSender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppMessageSender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppMessageSender), nil
}

type AppProfileStatus string

const (
	AppProfileStatusActive     AppProfileStatus = "active"
	AppProfileStatusSuperseded AppProfileStatus = "superseded"
	AppProfileStatusArchived   AppProfileStatus = "archived"
)

func (e *AppProfileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppProfileStatus(s)
	case string:
		*e = AppProfileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppProfileStatus: %T", src)
	}
	return nil
}

type NullAppProfileStatus struct {
	AppProfileStatus AppProfileStatus `json:"appProfileStatus"`
	Valid            bool             `json:"valid"` // Valid is true if AppProfileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppProfileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppProfileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppProfileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppProfileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppProfileStatus), nil
}

type AppResponseCategory string

const (
	AppResponseCategoryStrong        AppResponseCategory = "strong"
	AppResponseCategoryPartial       AppResponseCategory = "partial"
	AppResponseCategoryIncorrect     AppResponseCategory = "incorrect"
	AppResponseCategoryMisconception AppResponseCategory = "misconception"
	AppResponseCategoryDontKnow      AppResponseCategory = "dont_know"
)

func (e *AppResponseCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppResponseCategory(s)
	case string:
		*e = AppResponseCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for AppResponseCategory: %T", src)
	}
	return nil
}

type NullAppResponseCategory struct {
	AppResponseCategory AppResponseCategory `json:"appResponseCategory"`
	Valid               bool                `json:"valid"` // Valid is true if AppResponseCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppResponseCategory) Scan(value interface{}) error {
	if value == nil {
		ns.AppResponseCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppResponseCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppResponseCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppResponseCategory), nil
}

type AppReviewStatus string

const (
	AppReviewStatusPending  AppReviewStatus = "pending"
	AppReviewStatusReviewed AppReviewStatus = "reviewed"
	AppReviewStatusResolved AppReviewStatus = "resolved"
)

func (e *AppReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppReviewStatus(s)
	case string:
		*e = AppReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppReviewStatus: %T", src)
	}
	return nil
}

type NullAppReviewStatus struct {
	AppReviewStatus AppReviewStatus `json:"appReviewStatus"`
	Valid           bool            `json:"valid"` // Valid is true if AppReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppReviewStatus), nil
}

type AppSubmissionStatus string

const (
	AppSubmissionStatusDraft          AppSubmissionStatus = "draft"
	AppSubmissionStatusSubmitted      AppSubmissionStatus = "submitted"
	AppSubmissionStatusVivaInProgress AppSubmissionStatus = "viva_in_progress"
	AppSubmissionStatusVivaCompleted  AppSubmissionStatus = "viva_completed"
	AppSubmissionStatusReportReady    AppSubmissionStatus = "report_ready"
)

func (e *AppSubmissionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppSubmissionStatus(s)
	case string:
		*e = AppSubmissionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppSubmissionStatus: %T", src)
	}
	return nil
}

type NullAppSubmissionStatus struct {
	AppSubmissionStatus AppSubmissionStatus `json:"appSubmissionStatus"`
	Valid               bool                `json:"valid"` // Valid is true if AppSubmissionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppSubmissionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppSubmissionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppSubmissionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppSubmissionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppSubmissionStatus), nil
}

type AppTeacherDecision string

const (
	AppTeacherDecisionAuthenticConfirmed   AppTeacherDecision = "authentic_confirmed"
	AppTeacherDecisionAuthenticWithSupport AppTeacherDecision = "authentic_with_support"
	AppTeacherDecisionFollowUpRequired     AppTeacherDecision = "follow_up_required"
	AppTeacherDecisionConcernNotResolved   AppTeacherDecision = "concern_not_resolved"
)

func (e *AppTeacherDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppTeacherDecision(s)
	case string:
		*e = AppTeacherDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for AppTeacherDecision: %T", src)
	}
	return nil
}

type NullAppTeacherDecision struct {
	AppTeacherDecision AppTeacherDecision `json:"appTeacherDecision"`
	Valid              bool               `json:"valid"` // Valid is true if AppTeacherDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppTeacherDecision) Scan(value interface{}) error {
	if value == nil {
		ns.AppTeacherDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppTeacherDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppTeacherDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppTeacherDecision), nil
}

type AppWritingSourceType string

const (
	AppWritingSourceTypeBaselineInClass    AppWritingSourceType = "baseline_in_class"
	AppWritingSourceTypeBaselineSupervised AppWritingSourceType = "baseline_supervised"
	AppWritingSourceTypeAssessmentUpload   AppWritingSourceType = "assessment_upload"
	AppWritingSourceTypeVivaTranscript     AppWritingSourceType = "viva_transcript"
)

func (e *AppWritingSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppWritingSourceType(s)
	case string:
		*e = AppWritingSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for AppWritingSourceType: %T", src)
	}
	return nil
}

type NullAppWritingSourceType struct {
	AppWritingSourceType AppWritingSourceType `json:"appWritingSourceType"`
	Valid                bool                 `json:"valid"` // Valid is true if AppWritingSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppWritingSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.AppWritingSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppWritingSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppWritingSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppWritingSourceType), nil
}

type AppAuthorshipAnalysis struct {
	AuthorshipAnalysisID    pgtype.UUID                 `db:"authorship_analysis_id" json:"authorshipAnalysisId"`
	StudentID               pgtype.UUID                 `db:"student_id" json:"studentId"`
	StudentWritingSampleID  pgtype.UUID                 `db:"student_writing_sample_id" json:"studentWritingSampleId"`
	StudentProfileVersionID pgtype.UUID                 `db:"student_profile_version_id" json:"studentProfileVersionId"`
	DiscrepancyLevel        AppDiscrepancyLevel         `db:"discrepancy_level" json:"discrepancyLevel"`
	StylometricDistance     pgtype.Numeric              `db:"stylometric_distance" json:"stylometricDistance"`
	EmbeddingDistance       pgtype.Numeric              `db:"embedding_distance" json:"embeddingDistance"`
	FeatureDeltas           []byte                      `db:"feature_deltas" json:"featureDeltas"`
	Explanation             []byte                      `db:"explanation" json:"explanation"`
	Recommendation          AppAuthorshipRecommendation `db:"recommendation" json:"recommendation"`
	ModelVersion            pgtype.Text                 `db:"model_version" json:"modelVersion"`
	CreatedAt               pgtype.Timestamptz          `db:"created_at" json:"createdAt"`
}

type AppAuthorshipReport struct {
	ReportID     pgtype.UUID        `db:"report_id" json:"reportId"`
	SubmissionID pgtype.UUID        `db:"submission_id" json:"submissionId"`
	InterviewID  pgtype.UUID        `db:"interview_id" json:"interviewId"`
	Report       []byte             `db:"report" json:"report"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppAuthorshipReview struct {
	AuthorshipReviewID   pgtype.UUID            `db:"authorship_review_id" json:"authorshipReviewId"`
	AuthorshipAnalysisID pgtype.UUID            `db:"authorship_analysis_id" json:"authorshipAnalysisId"`
	TeacherID            pgtype.UUID            `db:"teacher_id" json:"teacherId"`
	ReviewStatus         AppReviewStatus        `db:"review_status" json:"reviewStatus"`
	TeacherDecision      NullAppTeacherDecision `db:"teacher_decision" json:"teacherDecision"`
	Notes                pgtype.Text            `db:"notes" json:"notes"`
	ReviewedAt           pgtype.Timestamptz     `db:"reviewed_at" json:"reviewedAt"`
	CreatedAt            pgtype.Timestamptz     `db:"created_at" json:"createdAt"`
}

type AppAuthorshipViva struct {
	AuthorshipVivaID           pgtype.UUID           `db:"authorship_viva_id" json:"authorshipVivaId"`
	AuthorshipAnalysisID       pgtype.UUID           `db:"authorship_analysis_id" json:"authorshipAnalysisId"`
	GeneratedQuestions         []byte                `db:"generated_questions" json:"generatedQuestions"`
	Transcript                 pgtype.Text           `db:"transcript" json:"transcript"`
	ConceptualAlignmentSummary []byte                `db:"conceptual_alignment_summary" json:"conceptualAlignmentSummary"`
	AlignmentLevel             NullAppAlignmentLevel `db:"alignment_level" json:"alignmentLevel"`
	AlignmentNotes             pgtype.Text           `db:"alignment_notes" json:"alignmentNotes"`
	CreatedAt                  pgtype.Timestamptz    `db:"created_at" json:"createdAt"`
}

type AppClass struct {
	ClassID   pgtype.UUID        `db:"class_id" json:"classId"`
	TeacherID pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	Name      string             `db:"name" json:"name"`
	ClassCode string             `db:"class_code" json:"classCode"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppConceptTag struct {
	ConceptTagID           pgtype.UUID        `db:"concept_tag_id" json:"conceptTagId"`
	Name                   string             `db:"name" json:"name"`
	DisplayName            pgtype.Text        `db:"display_name" json:"displayName"`
	Description            pgtype.Text        `db:"description" json:"description"`
	CurriculumDescriptorID pgtype.UUID        `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppCriterionEvidence struct {
	CriterionEvidenceID pgtype.UUID        `db:"criterion_evidence_id" json:"criterionEvidenceId"`
	InterviewSummaryID  pgtype.UUID        `db:"interview_summary_id" json:"interviewSummaryId"`
	RubricCriterionID   pgtype.UUID        `db:"rubric_criterion_id" json:"rubricCriterionId"`
	Level               pgtype.Text        `db:"level" json:"level"`
	EvidenceText        pgtype.Text        `db:"evidence_text" json:"evidenceText"`
	ModelConfidence     pgtype.Numeric     `db:"model_confidence" json:"modelConfidence"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppCurriculumDescriptor struct {
	CurriculumDescriptorID     pgtype.UUID        `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	Code                       string             `db:"code" json:"code"`
	Subject                    string             `db:"subject" json:"subject"`
	LevelBand                  string             `db:"level_band" json:"levelBand"`
	Strand                     pgtype.Text        `db:"strand" json:"strand"`
	Substrand                  pgtype.Text        `db:"substrand" json:"substrand"`
	Description                string             `db:"description" json:"description"`
	Elaborations               []byte             `db:"elaborations" json:"elaborations"`
	AchievementStandardExcerpt pgtype.Text        `db:"achievement_standard_excerpt" json:"achievementStandardExcerpt"`
	Metadata                   []byte             `db:"metadata" json:"metadata"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppInterview struct {
	InterviewID     pgtype.UUID        `db:"interview_id" json:"interviewId"`
	InterviewPlanID pgtype.UUID        `db:"interview_plan_id" json:"interviewPlanId"`
	TeacherID       pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	StudentID       pgtype.UUID        `db:"student_id" json:"studentId"`
	Simulated       bool               `db:"simulated" json:"simulated"`
	StudentName     pgtype.Text        `db:"student_name" json:"studentName"`
	Status          string             `db:"status" json:"status"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"startedAt"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completedAt"`
	SubmissionID    pgtype.UUID        `db:"submission_id" json:"submissionId"`
}

type AppInterviewMessage struct {
	InterviewMessageID  pgtype.UUID        `db:"interview_message_id" json:"interviewMessageId"`
	InterviewID         pgtype.UUID        `db:"interview_id" json:"interviewId"`
	Sender              string             `db:"sender" json:"sender"`
	InterviewQuestionID pgtype.UUID        `db:"interview_question_id" json:"interviewQuestionId"`
	Content             string             `db:"content" json:"content"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppInterviewPlan struct {
	InterviewPlanID     pgtype.UUID        `db:"interview_plan_id" json:"interviewPlanId"`
	RubricID            pgtype.UUID        `db:"rubric_id" json:"rubricId"`
	Title               string             `db:"title" json:"title"`
	Instructions        pgtype.Text        `db:"instructions" json:"instructions"`
	Config              []byte             `db:"config" json:"config"`
	Status              string             `db:"status" json:"status"`
	CurriculumSubject   pgtype.Text        `db:"curriculum_subject" json:"curriculumSubject"`
	CurriculumLevelBand pgtype.Text        `db:"curriculum_level_band" json:"curriculumLevelBand"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppInterviewPlanCurriculumDescriptor struct {
	InterviewPlanID        pgtype.UUID        `db:"interview_plan_id" json:"interviewPlanId"`
	CurriculumDescriptorID pgtype.UUID        `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	PrimaryAlignment       bool               `db:"primary_alignment" json:"primaryAlignment"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppInterviewQuestion struct {
	InterviewQuestionID pgtype.UUID        `db:"interview_question_id" json:"interviewQuestionId"`
	InterviewPlanID     pgtype.UUID        `db:"interview_plan_id" json:"interviewPlanId"`
	RubricCriterionID   pgtype.UUID        `db:"rubric_criterion_id" json:"rubricCriterionId"`
	Prompt              string             `db:"prompt" json:"prompt"`
	QuestionType        string             `db:"question_type" json:"questionType"`
	OrderIndex          int32              `db:"order_index" json:"orderIndex"`
	IsActive            bool               `db:"is_active" json:"isActive"`
	FollowUpToID        pgtype.UUID        `db:"follow_up_to_id" json:"followUpToId"`
	FollowUpCondition   pgtype.Text        `db:"follow_up_condition" json:"followUpCondition"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppInterviewQuestionBranch struct {
	InterviewQuestionBranchID pgtype.UUID        `db:"interview_question_branch_id" json:"interviewQuestionBranchId"`
	ParentQuestionID          pgtype.UUID        `db:"parent_question_id" json:"parentQuestionId"`
	ResponseCategory          string             `db:"response_category" json:"responseCategory"`
	MisconceptionTagID        pgtype.UUID        `db:"misconception_tag_id" json:"misconceptionTagId"`
	NextQuestionID            pgtype.UUID        `db:"next_question_id" json:"nextQuestionId"`
	FollowUpPromptOverride    pgtype.Text        `db:"follow_up_prompt_override" json:"followUpPromptOverride"`
	TerminateInterview        bool               `db:"terminate_interview" json:"terminateInterview"`
	OrderIndex                int32              `db:"order_index" json:"orderIndex"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppInterviewQuestionConceptTag struct {
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
	ConceptTagID        pgtype.UUID `db:"concept_tag_id" json:"conceptTagId"`
}

type AppInterviewQuestionMisconceptionTag struct {
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
	MisconceptionTagID  pgtype.UUID `db:"misconception_tag_id" json:"misconceptionTagId"`
}

type AppInterviewSummary struct {
	InterviewSummaryID pgtype.UUID        `db:"interview_summary_id" json:"interviewSummaryId"`
	InterviewID        pgtype.UUID        `db:"interview_id" json:"interviewId"`
	OverallSummary     pgtype.Text        `db:"overall_summary" json:"overallSummary"`
	Strengths          pgtype.Text        `db:"strengths" json:"strengths"`
	AreasForGrowth     pgtype.Text        `db:"areas_for_growth" json:"areasForGrowth"`
	SuggestedNextSteps pgtype.Text        `db:"suggested_next_steps" json:"suggestedNextSteps"`
	RawLlmOutput       []byte             `db:"raw_llm_output" json:"rawLlmOutput"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppMisconceptionTag struct {
	MisconceptionTagID     pgtype.UUID        `db:"misconception_tag_id" json:"misconceptionTagId"`
	Name                   string             `db:"name" json:"name"`
	DisplayName            pgtype.Text        `db:"display_name" json:"displayName"`
	Description            pgtype.Text        `db:"description" json:"description"`
	ConceptTagID           pgtype.UUID        `db:"concept_tag_id" json:"conceptTagId"`
	CurriculumDescriptorID pgtype.UUID        `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppRoster struct {
	ClassID   pgtype.UUID        `db:"class_id" json:"classId"`
	StudentID pgtype.UUID        `db:"student_id" json:"studentId"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

type AppRubric struct {
	RubricID    pgtype.UUID        `db:"rubric_id" json:"rubricId"`
	TeacherID   pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	Title       string             `db:"title" json:"title"`
	Description pgtype.Text        `db:"description" json:"description"`
	RawText     string             `db:"raw_text" json:"rawText"`
	IsEnabled   bool               `db:"is_enabled" json:"isEnabled"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppRubricCriterium struct {
	RubricCriterionID pgtype.UUID        `db:"rubric_criterion_id" json:"rubricCriterionId"`
	RubricID          pgtype.UUID        `db:"rubric_id" json:"rubricId"`
	Name              string             `db:"name" json:"name"`
	Description       pgtype.Text        `db:"description" json:"description"`
	Weight            pgtype.Numeric     `db:"weight" json:"weight"`
	OrderIndex        int32              `db:"order_index" json:"orderIndex"`
	Levels            []byte             `db:"levels" json:"levels"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppStudent struct {
	StudentID   pgtype.UUID        `db:"student_id" json:"studentId"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"displayName"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppStudentProfile struct {
	StudentProfileID pgtype.UUID        `db:"student_profile_id" json:"studentProfileId"`
	StudentID        pgtype.UUID        `db:"student_id" json:"studentId"`
	Profile          []byte             `db:"profile" json:"profile"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppStudentProfileBaselineSample struct {
	StudentProfileVersionID pgtype.UUID `db:"student_profile_version_id" json:"studentProfileVersionId"`
	StudentWritingSampleID  pgtype.UUID `db:"student_writing_sample_id" json:"studentWritingSampleId"`
}

type AppStudentProfileVersion struct {
	StudentProfileVersionID pgtype.UUID        `db:"student_profile_version_id" json:"studentProfileVersionId"`
	StudentID               pgtype.UUID        `db:"student_id" json:"studentId"`
	Semester                string             `db:"semester" json:"semester"`
	Version                 int32              `db:"version" json:"version"`
	ProfileStatus           AppProfileStatus   `db:"profile_status" json:"profileStatus"`
	FeatureSummary          []byte             `db:"feature_summary" json:"featureSummary"`
	ModelVersion            pgtype.Text        `db:"model_version" json:"modelVersion"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppStudentWritingSample struct {
	StudentWritingSampleID pgtype.UUID          `db:"student_writing_sample_id" json:"studentWritingSampleId"`
	StudentID              pgtype.UUID          `db:"student_id" json:"studentId"`
	Semester               string               `db:"semester" json:"semester"`
	AssignmentName         pgtype.Text          `db:"assignment_name" json:"assignmentName"`
	SourceType             AppWritingSourceType `db:"source_type" json:"sourceType"`
	WrittenAt              pgtype.Timestamptz   `db:"written_at" json:"writtenAt"`
	TextContent            string               `db:"text_content" json:"textContent"`
	IsTeacherVerified      bool                 `db:"is_teacher_verified" json:"isTeacherVerified"`
	RawFeatures            []byte               `db:"raw_features" json:"rawFeatures"`
	CreatedAt              pgtype.Timestamptz   `db:"created_at" json:"createdAt"`
}

type AppSubmission struct {
	SubmissionID pgtype.UUID        `db:"submission_id" json:"submissionId"`
	StudentID    pgtype.UUID        `db:"student_id" json:"studentId"`
	RubricID     pgtype.UUID        `db:"rubric_id" json:"rubricId"`
	Status       string             `db:"status" json:"status"`
	Title        pgtype.Text        `db:"title" json:"title"`
	Notes        pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppSubmissionArtifact struct {
	ArtifactID   pgtype.UUID        `db:"artifact_id" json:"artifactId"`
	SubmissionID pgtype.UUID        `db:"submission_id" json:"submissionId"`
	ArtifactType string             `db:"artifact_type" json:"artifactType"`
	Payload      []byte             `db:"payload" json:"payload"`
	OrderIndex   int32              `db:"order_index" json:"orderIndex"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppTeacher struct {
	TeacherID    pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	Email        string             `db:"email" json:"email"`
	FullName     string             `db:"full_name" json:"fullName"`
	PasswordHash pgtype.Text        `db:"password_hash" json:"passwordHash"`
	IsEnabled    bool               `db:"is_enabled" json:"isEnabled"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}
