// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppInterviewStatus string

const (
	AppInterviewStatusDraft      AppInterviewStatus = "draft"
	AppInterviewStatusInProgress AppInterviewStatus = "in_progress"
	AppInterviewStatusCompleted  AppInterviewStatus = "completed"
)

func (e *AppInterviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppInterviewStatus(s)
	case string:
		*e = AppInterviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppInterviewStatus: %T", src)
	}
	return nil
}

type NullAppInterviewStatus struct {
	AppInterviewStatus AppInterviewStatus `json:"appInterviewStatus"`
	Valid              bool               `json:"valid"` // Valid is true if AppInterviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppInterviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppInterviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppInterviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppInterviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppInterviewStatus), nil
}

type AppMessageSender string

const (
	AppMessageSenderAi   AppMessageSender = "ai"
	AppMessageSenderUser AppMessageSender = "user"
)

func (e *AppMessageSender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppMessageSender(s)
	case string:
		*e = AppMessageSender(s)
	default:
		return fmt.Errorf("unsupported scan type for AppMessageSender: %T", src)
	}
	return nil
}

type NullAppMessageSender struct {
	AppMessageSender AppMessageSender `json:"appMessageSender"`
	Valid            bool             `json:"valid"` // Valid is true if AppMessageSender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppMessageSender) Scan(value interface{}) error {
	if value == nil {
		ns.AppMessageSender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppMessageSender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppMessageSender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppMessageSender), nil
}

type AppResponseCategory string

const (
	AppResponseCategoryStrong        AppResponseCategory = "strong"
	AppResponseCategoryPartial       AppResponseCategory = "partial"
	AppResponseCategoryIncorrect     AppResponseCategory = "incorrect"
	AppResponseCategoryMisconception AppResponseCategory = "misconception"
	AppResponseCategoryDontKnow      AppResponseCategory = "dont_know"
)

func (e *AppResponseCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppResponseCategory(s)
	case string:
		*e = AppResponseCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for AppResponseCategory: %T", src)
	}
	return nil
}

type NullAppResponseCategory struct {
	AppResponseCategory AppResponseCategory `json:"appResponseCategory"`
	Valid               bool                `json:"valid"` // Valid is true if AppResponseCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppResponseCategory) Scan(value interface{}) error {
	if value == nil {
		ns.AppResponseCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppResponseCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppResponseCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppResponseCategory), nil
}

type AppClass struct {
	ClassID   pgtype.UUID        `db:"class_id" json:"classId"`
	TeacherID pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	Name      string             `db:"name" json:"name"`
	ClassCode string             `db:"class_code" json:"classCode"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppConceptTag struct {
	ConceptTagID           pgtype.UUID        `db:"concept_tag_id" json:"conceptTagId"`
	Name                   string             `db:"name" json:"name"`
	DisplayName            pgtype.Text        `db:"display_name" json:"displayName"`
	Description            pgtype.Text        `db:"description" json:"description"`
	CurriculumDescriptorID pgtype.UUID        `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppCriterionEvidence struct {
	CriterionEvidenceID pgtype.UUID        `db:"criterion_evidence_id" json:"criterionEvidenceId"`
	InterviewSummaryID  pgtype.UUID        `db:"interview_summary_id" json:"interviewSummaryId"`
	RubricCriterionID   pgtype.UUID        `db:"rubric_criterion_id" json:"rubricCriterionId"`
	Level               pgtype.Text        `db:"level" json:"level"`
	EvidenceText        pgtype.Text        `db:"evidence_text" json:"evidenceText"`
	ModelConfidence     pgtype.Numeric     `db:"model_confidence" json:"modelConfidence"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppCurriculumDescriptor struct {
	CurriculumDescriptorID     pgtype.UUID        `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	Code                       string             `db:"code" json:"code"`
	Subject                    string             `db:"subject" json:"subject"`
	LevelBand                  string             `db:"level_band" json:"levelBand"`
	Strand                     pgtype.Text        `db:"strand" json:"strand"`
	Substrand                  pgtype.Text        `db:"substrand" json:"substrand"`
	Description                string             `db:"description" json:"description"`
	Elaborations               []byte             `db:"elaborations" json:"elaborations"`
	AchievementStandardExcerpt pgtype.Text        `db:"achievement_standard_excerpt" json:"achievementStandardExcerpt"`
	Metadata                   []byte             `db:"metadata" json:"metadata"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppInterview struct {
	InterviewID     pgtype.UUID        `db:"interview_id" json:"interviewId"`
	InterviewPlanID pgtype.UUID        `db:"interview_plan_id" json:"interviewPlanId"`
	TeacherID       pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	Simulated       bool               `db:"simulated" json:"simulated"`
	StudentName     pgtype.Text        `db:"student_name" json:"studentName"`
	Status          string             `db:"status" json:"status"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"startedAt"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completedAt"`
}

type AppInterviewMessage struct {
	InterviewMessageID  pgtype.UUID        `db:"interview_message_id" json:"interviewMessageId"`
	InterviewID         pgtype.UUID        `db:"interview_id" json:"interviewId"`
	Sender              string             `db:"sender" json:"sender"`
	InterviewQuestionID pgtype.UUID        `db:"interview_question_id" json:"interviewQuestionId"`
	Content             string             `db:"content" json:"content"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppInterviewPlan struct {
	InterviewPlanID     pgtype.UUID        `db:"interview_plan_id" json:"interviewPlanId"`
	RubricID            pgtype.UUID        `db:"rubric_id" json:"rubricId"`
	Title               string             `db:"title" json:"title"`
	Instructions        pgtype.Text        `db:"instructions" json:"instructions"`
	Config              []byte             `db:"config" json:"config"`
	Status              string             `db:"status" json:"status"`
	CurriculumSubject   pgtype.Text        `db:"curriculum_subject" json:"curriculumSubject"`
	CurriculumLevelBand pgtype.Text        `db:"curriculum_level_band" json:"curriculumLevelBand"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppInterviewPlanCurriculumDescriptor struct {
	InterviewPlanID        pgtype.UUID        `db:"interview_plan_id" json:"interviewPlanId"`
	CurriculumDescriptorID pgtype.UUID        `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	PrimaryAlignment       bool               `db:"primary_alignment" json:"primaryAlignment"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppInterviewQuestion struct {
	InterviewQuestionID pgtype.UUID        `db:"interview_question_id" json:"interviewQuestionId"`
	InterviewPlanID     pgtype.UUID        `db:"interview_plan_id" json:"interviewPlanId"`
	RubricCriterionID   pgtype.UUID        `db:"rubric_criterion_id" json:"rubricCriterionId"`
	Prompt              string             `db:"prompt" json:"prompt"`
	QuestionType        string             `db:"question_type" json:"questionType"`
	OrderIndex          int32              `db:"order_index" json:"orderIndex"`
	IsActive            bool               `db:"is_active" json:"isActive"`
	FollowUpToID        pgtype.UUID        `db:"follow_up_to_id" json:"followUpToId"`
	FollowUpCondition   pgtype.Text        `db:"follow_up_condition" json:"followUpCondition"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppInterviewQuestionBranch struct {
	InterviewQuestionBranchID pgtype.UUID        `db:"interview_question_branch_id" json:"interviewQuestionBranchId"`
	ParentQuestionID          pgtype.UUID        `db:"parent_question_id" json:"parentQuestionId"`
	ResponseCategory          string             `db:"response_category" json:"responseCategory"`
	MisconceptionTagID        pgtype.UUID        `db:"misconception_tag_id" json:"misconceptionTagId"`
	NextQuestionID            pgtype.UUID        `db:"next_question_id" json:"nextQuestionId"`
	FollowUpPromptOverride    pgtype.Text        `db:"follow_up_prompt_override" json:"followUpPromptOverride"`
	TerminateInterview        bool               `db:"terminate_interview" json:"terminateInterview"`
	OrderIndex                int32              `db:"order_index" json:"orderIndex"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppInterviewQuestionConceptTag struct {
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
	ConceptTagID        pgtype.UUID `db:"concept_tag_id" json:"conceptTagId"`
}

type AppInterviewQuestionMisconceptionTag struct {
	InterviewQuestionID pgtype.UUID `db:"interview_question_id" json:"interviewQuestionId"`
	MisconceptionTagID  pgtype.UUID `db:"misconception_tag_id" json:"misconceptionTagId"`
}

type AppInterviewSummary struct {
	InterviewSummaryID pgtype.UUID        `db:"interview_summary_id" json:"interviewSummaryId"`
	InterviewID        pgtype.UUID        `db:"interview_id" json:"interviewId"`
	OverallSummary     pgtype.Text        `db:"overall_summary" json:"overallSummary"`
	Strengths          pgtype.Text        `db:"strengths" json:"strengths"`
	AreasForGrowth     pgtype.Text        `db:"areas_for_growth" json:"areasForGrowth"`
	SuggestedNextSteps pgtype.Text        `db:"suggested_next_steps" json:"suggestedNextSteps"`
	RawLlmOutput       []byte             `db:"raw_llm_output" json:"rawLlmOutput"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type AppMisconceptionTag struct {
	MisconceptionTagID     pgtype.UUID        `db:"misconception_tag_id" json:"misconceptionTagId"`
	Name                   string             `db:"name" json:"name"`
	DisplayName            pgtype.Text        `db:"display_name" json:"displayName"`
	Description            pgtype.Text        `db:"description" json:"description"`
	ConceptTagID           pgtype.UUID        `db:"concept_tag_id" json:"conceptTagId"`
	CurriculumDescriptorID pgtype.UUID        `db:"curriculum_descriptor_id" json:"curriculumDescriptorId"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppRoster struct {
	ClassID   pgtype.UUID        `db:"class_id" json:"classId"`
	StudentID pgtype.UUID        `db:"student_id" json:"studentId"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

type AppRubric struct {
	RubricID    pgtype.UUID        `db:"rubric_id" json:"rubricId"`
	TeacherID   pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	Title       string             `db:"title" json:"title"`
	Description pgtype.Text        `db:"description" json:"description"`
	RawText     string             `db:"raw_text" json:"rawText"`
	IsEnabled   bool               `db:"is_enabled" json:"isEnabled"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppRubricCriterium struct {
	RubricCriterionID pgtype.UUID        `db:"rubric_criterion_id" json:"rubricCriterionId"`
	RubricID          pgtype.UUID        `db:"rubric_id" json:"rubricId"`
	Name              string             `db:"name" json:"name"`
	Description       pgtype.Text        `db:"description" json:"description"`
	Weight            pgtype.Numeric     `db:"weight" json:"weight"`
	OrderIndex        int32              `db:"order_index" json:"orderIndex"`
	Levels            []byte             `db:"levels" json:"levels"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppStudent struct {
	StudentID   pgtype.UUID        `db:"student_id" json:"studentId"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"displayName"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}

type AppTeacher struct {
	TeacherID    pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	Email        string             `db:"email" json:"email"`
	FullName     string             `db:"full_name" json:"fullName"`
	PasswordHash pgtype.Text        `db:"password_hash" json:"passwordHash"`
	IsEnabled    bool               `db:"is_enabled" json:"isEnabled"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
}
