// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roster.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToRoster = `-- name: AddToRoster :one
INSERT INTO app.roster (class_id, student_id)
VALUES ($1::uuid, $2::uuid)
RETURNING class_id, student_id, joined_at
`

type AddToRosterParams struct {
	ClassID   pgtype.UUID `db:"class_id" json:"classId"`
	StudentID pgtype.UUID `db:"student_id" json:"studentId"`
}

func (q *Queries) AddToRoster(ctx context.Context, arg AddToRosterParams) (AppRoster, error) {
	row := q.db.QueryRow(ctx, addToRoster, arg.ClassID, arg.StudentID)
	var i AppRoster
	err := row.Scan(&i.ClassID, &i.StudentID, &i.JoinedAt)
	return i, err
}

const isStudentInClass = `-- name: IsStudentInClass :one
SELECT EXISTS(
    SELECT 1 FROM app.roster
    WHERE class_id = $1::uuid AND student_id = $2::uuid
) AS in_class
`

type IsStudentInClassParams struct {
	ClassID   pgtype.UUID `db:"class_id" json:"classId"`
	StudentID pgtype.UUID `db:"student_id" json:"studentId"`
}

func (q *Queries) IsStudentInClass(ctx context.Context, arg IsStudentInClassParams) (bool, error) {
	row := q.db.QueryRow(ctx, isStudentInClass, arg.ClassID, arg.StudentID)
	var in_class bool
	err := row.Scan(&in_class)
	return in_class, err
}

const listClassesByStudent = `-- name: ListClassesByStudent :many
SELECT c.class_id, c.teacher_id, c.name, c.class_code, c.created_at, c.updated_at,
       r.joined_at
FROM app.roster r
JOIN app.classes c ON c.class_id = r.class_id
WHERE r.student_id = $1::uuid
ORDER BY c.name ASC
`

type ListClassesByStudentRow struct {
	ClassID   pgtype.UUID        `db:"class_id" json:"classId"`
	TeacherID pgtype.UUID        `db:"teacher_id" json:"teacherId"`
	Name      string             `db:"name" json:"name"`
	ClassCode string             `db:"class_code" json:"classCode"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

func (q *Queries) ListClassesByStudent(ctx context.Context, studentID pgtype.UUID) ([]ListClassesByStudentRow, error) {
	rows, err := q.db.Query(ctx, listClassesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassesByStudentRow
	for rows.Next() {
		var i ListClassesByStudentRow
		if err := rows.Scan(
			&i.ClassID,
			&i.TeacherID,
			&i.Name,
			&i.ClassCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterByClass = `-- name: ListRosterByClass :many
SELECT r.class_id, r.student_id, r.joined_at,
       s.email AS student_email, s.display_name AS student_display_name
FROM app.roster r
JOIN app.students s ON s.student_id = r.student_id
WHERE r.class_id = $1::uuid
ORDER BY s.display_name ASC, r.joined_at ASC
`

type ListRosterByClassRow struct {
	ClassID            pgtype.UUID        `db:"class_id" json:"classId"`
	StudentID          pgtype.UUID        `db:"student_id" json:"studentId"`
	JoinedAt           pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	StudentEmail       string             `db:"student_email" json:"studentEmail"`
	StudentDisplayName string             `db:"student_display_name" json:"studentDisplayName"`
}

func (q *Queries) ListRosterByClass(ctx context.Context, classID pgtype.UUID) ([]ListRosterByClassRow, error) {
	rows, err := q.db.Query(ctx, listRosterByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosterByClassRow
	for rows.Next() {
		var i ListRosterByClassRow
		if err := rows.Scan(
			&i.ClassID,
			&i.StudentID,
			&i.JoinedAt,
			&i.StudentEmail,
			&i.StudentDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromRoster = `-- name: RemoveFromRoster :exec
DELETE FROM app.roster
WHERE class_id = $1::uuid
  AND student_id = $2::uuid
`

type RemoveFromRosterParams struct {
	ClassID   pgtype.UUID `db:"class_id" json:"classId"`
	StudentID pgtype.UUID `db:"student_id" json:"studentId"`
}

func (q *Queries) RemoveFromRoster(ctx context.Context, arg RemoveFromRosterParams) error {
	_, err := q.db.Exec(ctx, removeFromRoster, arg.ClassID, arg.StudentID)
	return err
}
