// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rubric_criteria.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRubricCriterion = `-- name: CreateRubricCriterion :one
INSERT INTO app.rubric_criteria (rubric_id, name, description, weight, order_index, levels)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5,
    $6::jsonb
)
RETURNING rubric_criterion_id, rubric_id, name, description, weight, order_index, levels, created_at, updated_at
`

type CreateRubricCriterionParams struct {
	RubricID    pgtype.UUID    `db:"rubric_id" json:"rubricId"`
	Name        string         `db:"name" json:"name"`
	Description pgtype.Text    `db:"description" json:"description"`
	Weight      pgtype.Numeric `db:"weight" json:"weight"`
	OrderIndex  int32          `db:"order_index" json:"orderIndex"`
	Levels      []byte         `db:"levels" json:"levels"`
}

func (q *Queries) CreateRubricCriterion(ctx context.Context, arg CreateRubricCriterionParams) (AppRubricCriterium, error) {
	row := q.db.QueryRow(ctx, createRubricCriterion,
		arg.RubricID,
		arg.Name,
		arg.Description,
		arg.Weight,
		arg.OrderIndex,
		arg.Levels,
	)
	var i AppRubricCriterium
	err := row.Scan(
		&i.RubricCriterionID,
		&i.RubricID,
		&i.Name,
		&i.Description,
		&i.Weight,
		&i.OrderIndex,
		&i.Levels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCriteriaByRubric = `-- name: DeleteCriteriaByRubric :exec
DELETE FROM app.rubric_criteria
WHERE rubric_id = $1::uuid
`

func (q *Queries) DeleteCriteriaByRubric(ctx context.Context, rubricID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCriteriaByRubric, rubricID)
	return err
}

const listCriteriaByRubric = `-- name: ListCriteriaByRubric :many
SELECT rubric_criterion_id, rubric_id, name, description, weight, order_index, levels, created_at, updated_at
FROM app.rubric_criteria
WHERE rubric_id = $1::uuid
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListCriteriaByRubric(ctx context.Context, rubricID pgtype.UUID) ([]AppRubricCriterium, error) {
	rows, err := q.db.Query(ctx, listCriteriaByRubric, rubricID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppRubricCriterium
	for rows.Next() {
		var i AppRubricCriterium
		if err := rows.Scan(
			&i.RubricCriterionID,
			&i.RubricID,
			&i.Name,
			&i.Description,
			&i.Weight,
			&i.OrderIndex,
			&i.Levels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
