// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rubrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRubric = `-- name: CreateRubric :one
INSERT INTO app.rubrics (teacher_id, title, description, raw_text)
VALUES ($1::uuid, $2, $3, $4)
RETURNING rubric_id, teacher_id, title, description, raw_text, is_enabled, created_at, updated_at
`

type CreateRubricParams struct {
	TeacherID   pgtype.UUID `db:"teacher_id" json:"teacherId"`
	Title       string      `db:"title" json:"title"`
	Description pgtype.Text `db:"description" json:"description"`
	RawText     string      `db:"raw_text" json:"rawText"`
}

func (q *Queries) CreateRubric(ctx context.Context, arg CreateRubricParams) (AppRubric, error) {
	row := q.db.QueryRow(ctx, createRubric,
		arg.TeacherID,
		arg.Title,
		arg.Description,
		arg.RawText,
	)
	var i AppRubric
	err := row.Scan(
		&i.RubricID,
		&i.TeacherID,
		&i.Title,
		&i.Description,
		&i.RawText,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableRubric = `-- name: DisableRubric :exec
UPDATE app.rubrics
SET is_enabled = FALSE,
    updated_at = NOW()
WHERE rubric_id = $1::uuid
`

func (q *Queries) DisableRubric(ctx context.Context, rubricID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableRubric, rubricID)
	return err
}

const getRubricByID = `-- name: GetRubricByID :one
SELECT rubric_id, teacher_id, title, description, raw_text, is_enabled, created_at, updated_at
FROM app.rubrics
WHERE rubric_id = $1::uuid
`

func (q *Queries) GetRubricByID(ctx context.Context, rubricID pgtype.UUID) (AppRubric, error) {
	row := q.db.QueryRow(ctx, getRubricByID, rubricID)
	var i AppRubric
	err := row.Scan(
		&i.RubricID,
		&i.TeacherID,
		&i.Title,
		&i.Description,
		&i.RawText,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRubricsByTeacher = `-- name: ListRubricsByTeacher :many
SELECT rubric_id, teacher_id, title, description, raw_text, is_enabled, created_at, updated_at
FROM app.rubrics
WHERE teacher_id = $1::uuid
ORDER BY created_at DESC
`

func (q *Queries) ListRubricsByTeacher(ctx context.Context, teacherID pgtype.UUID) ([]AppRubric, error) {
	rows, err := q.db.Query(ctx, listRubricsByTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppRubric
	for rows.Next() {
		var i AppRubric
		if err := rows.Scan(
			&i.RubricID,
			&i.TeacherID,
			&i.Title,
			&i.Description,
			&i.RawText,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRubric = `-- name: UpdateRubric :one
UPDATE app.rubrics
SET title = COALESCE($1, title),
    description = COALESCE($2, description),
    raw_text = COALESCE($3, raw_text),
    updated_at = NOW()
WHERE rubric_id = $4::uuid
RETURNING rubric_id, teacher_id, title, description, raw_text, is_enabled, created_at, updated_at
`

type UpdateRubricParams struct {
	Title       pgtype.Text `db:"title" json:"title"`
	Description pgtype.Text `db:"description" json:"description"`
	RawText     pgtype.Text `db:"raw_text" json:"rawText"`
	RubricID    pgtype.UUID `db:"rubric_id" json:"rubricId"`
}

func (q *Queries) UpdateRubric(ctx context.Context, arg UpdateRubricParams) (AppRubric, error) {
	row := q.db.QueryRow(ctx, updateRubric,
		arg.Title,
		arg.Description,
		arg.RawText,
		arg.RubricID,
	)
	var i AppRubric
	err := row.Scan(
		&i.RubricID,
		&i.TeacherID,
		&i.Title,
		&i.Description,
		&i.RawText,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
