// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudentProfile = `-- name: CreateStudentProfile :one
INSERT INTO app.student_profiles (student_id, profile)
VALUES ($1::uuid, $2::jsonb)
RETURNING student_profile_id, student_id, profile, created_at
`

type CreateStudentProfileParams struct {
	StudentID pgtype.UUID `db:"student_id" json:"studentId"`
	Profile   []byte      `db:"profile" json:"profile"`
}

func (q *Queries) CreateStudentProfile(ctx context.Context, arg CreateStudentProfileParams) (AppStudentProfile, error) {
	row := q.db.QueryRow(ctx, createStudentProfile, arg.StudentID, arg.Profile)
	var i AppStudentProfile
	err := row.Scan(
		&i.StudentProfileID,
		&i.StudentID,
		&i.Profile,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestStudentProfileByStudent = `-- name: GetLatestStudentProfileByStudent :one
SELECT student_profile_id, student_id, profile, created_at
FROM app.student_profiles
WHERE student_id = $1::uuid
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestStudentProfileByStudent(ctx context.Context, studentID pgtype.UUID) (AppStudentProfile, error) {
	row := q.db.QueryRow(ctx, getLatestStudentProfileByStudent, studentID)
	var i AppStudentProfile
	err := row.Scan(
		&i.StudentProfileID,
		&i.StudentID,
		&i.Profile,
		&i.CreatedAt,
	)
	return i, err
}
