// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO app.students (email, display_name)
VALUES ($1, $2)
RETURNING student_id, email, display_name, created_at, updated_at
`

type CreateStudentParams struct {
	Email       string `db:"email" json:"email"`
	DisplayName string `db:"display_name" json:"displayName"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (AppStudent, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.Email, arg.DisplayName)
	var i AppStudent
	err := row.Scan(
		&i.StudentID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByEmail = `-- name: GetStudentByEmail :one
SELECT student_id, email, display_name, created_at, updated_at
FROM app.students
WHERE email = $1
`

func (q *Queries) GetStudentByEmail(ctx context.Context, email string) (AppStudent, error) {
	row := q.db.QueryRow(ctx, getStudentByEmail, email)
	var i AppStudent
	err := row.Scan(
		&i.StudentID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT student_id, email, display_name, created_at, updated_at
FROM app.students
WHERE student_id = $1::uuid
`

func (q *Queries) GetStudentByID(ctx context.Context, studentID pgtype.UUID) (AppStudent, error) {
	row := q.db.QueryRow(ctx, getStudentByID, studentID)
	var i AppStudent
	err := row.Scan(
		&i.StudentID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT student_id, email, display_name, created_at, updated_at
FROM app.students
ORDER BY display_name ASC, created_at DESC
`

func (q *Queries) ListStudents(ctx context.Context) ([]AppStudent, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppStudent
	for rows.Next() {
		var i AppStudent
		if err := rows.Scan(
			&i.StudentID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE app.students
SET display_name = $1,
    updated_at   = NOW()
WHERE student_id = $2::uuid
RETURNING student_id, email, display_name, created_at, updated_at
`

type UpdateStudentParams struct {
	DisplayName string      `db:"display_name" json:"displayName"`
	StudentID   pgtype.UUID `db:"student_id" json:"studentId"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (AppStudent, error) {
	row := q.db.QueryRow(ctx, updateStudent, arg.DisplayName, arg.StudentID)
	var i AppStudent
	err := row.Scan(
		&i.StudentID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
