// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO app.submissions (student_id, rubric_id, status, title, notes)
VALUES (
    $1::uuid,
    $2::uuid,
    COALESCE($3::app.submission_status, 'draft'::app.submission_status),
    $4,
    $5
)
RETURNING submission_id, student_id, rubric_id, status, title, notes, created_at, updated_at
`

type CreateSubmissionParams struct {
	StudentID pgtype.UUID `db:"student_id" json:"studentId"`
	RubricID  pgtype.UUID `db:"rubric_id" json:"rubricId"`
	Status    string      `db:"status" json:"status"`
	Title     pgtype.Text `db:"title" json:"title"`
	Notes     pgtype.Text `db:"notes" json:"notes"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (AppSubmission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.StudentID,
		arg.RubricID,
		arg.Status,
		arg.Title,
		arg.Notes,
	)
	var i AppSubmission
	err := row.Scan(
		&i.SubmissionID,
		&i.StudentID,
		&i.RubricID,
		&i.Status,
		&i.Title,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT submission_id, student_id, rubric_id, status, title, notes, created_at, updated_at
FROM app.submissions
WHERE submission_id = $1::uuid
`

func (q *Queries) GetSubmissionByID(ctx context.Context, submissionID pgtype.UUID) (AppSubmission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, submissionID)
	var i AppSubmission
	err := row.Scan(
		&i.SubmissionID,
		&i.StudentID,
		&i.RubricID,
		&i.Status,
		&i.Title,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubmissionsByRubric = `-- name: ListSubmissionsByRubric :many
SELECT submission_id, student_id, rubric_id, status, title, notes, created_at, updated_at
FROM app.submissions
WHERE rubric_id = $1::uuid
ORDER BY created_at DESC
`

func (q *Queries) ListSubmissionsByRubric(ctx context.Context, rubricID pgtype.UUID) ([]AppSubmission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByRubric, rubricID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSubmission
	for rows.Next() {
		var i AppSubmission
		if err := rows.Scan(
			&i.SubmissionID,
			&i.StudentID,
			&i.RubricID,
			&i.Status,
			&i.Title,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByStudent = `-- name: ListSubmissionsByStudent :many
SELECT submission_id, student_id, rubric_id, status, title, notes, created_at, updated_at
FROM app.submissions
WHERE student_id = $1::uuid
ORDER BY created_at DESC
`

func (q *Queries) ListSubmissionsByStudent(ctx context.Context, studentID pgtype.UUID) ([]AppSubmission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSubmission
	for rows.Next() {
		var i AppSubmission
		if err := rows.Scan(
			&i.SubmissionID,
			&i.StudentID,
			&i.RubricID,
			&i.Status,
			&i.Title,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmissionStatus = `-- name: UpdateSubmissionStatus :exec
UPDATE app.submissions
SET status = $1::app.submission_status,
    updated_at = NOW()
WHERE submission_id = $2::uuid
`

type UpdateSubmissionStatusParams struct {
	Status       string      `db:"status" json:"status"`
	SubmissionID pgtype.UUID `db:"submission_id" json:"submissionId"`
}

func (q *Queries) UpdateSubmissionStatus(ctx context.Context, arg UpdateSubmissionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubmissionStatus, arg.Status, arg.SubmissionID)
	return err
}
