// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submission_artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmissionArtifact = `-- name: CreateSubmissionArtifact :one
INSERT INTO app.submission_artifacts (submission_id, artifact_type, payload, order_index)
VALUES (
    $1::uuid,
    $2::app.artifact_type,
    COALESCE($3::jsonb, '{}'::jsonb),
    COALESCE($4, 0)
)
RETURNING artifact_id, submission_id, artifact_type, payload, order_index, created_at
`

type CreateSubmissionArtifactParams struct {
	SubmissionID pgtype.UUID `db:"submission_id" json:"submissionId"`
	ArtifactType string      `db:"artifact_type" json:"artifactType"`
	Payload      []byte      `db:"payload" json:"payload"`
	OrderIndex   interface{} `db:"order_index" json:"orderIndex"`
}

func (q *Queries) CreateSubmissionArtifact(ctx context.Context, arg CreateSubmissionArtifactParams) (AppSubmissionArtifact, error) {
	row := q.db.QueryRow(ctx, createSubmissionArtifact,
		arg.SubmissionID,
		arg.ArtifactType,
		arg.Payload,
		arg.OrderIndex,
	)
	var i AppSubmissionArtifact
	err := row.Scan(
		&i.ArtifactID,
		&i.SubmissionID,
		&i.ArtifactType,
		&i.Payload,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionArtifactByID = `-- name: GetSubmissionArtifactByID :one
SELECT artifact_id, submission_id, artifact_type, payload, order_index, created_at
FROM app.submission_artifacts
WHERE artifact_id = $1::uuid
`

func (q *Queries) GetSubmissionArtifactByID(ctx context.Context, artifactID pgtype.UUID) (AppSubmissionArtifact, error) {
	row := q.db.QueryRow(ctx, getSubmissionArtifactByID, artifactID)
	var i AppSubmissionArtifact
	err := row.Scan(
		&i.ArtifactID,
		&i.SubmissionID,
		&i.ArtifactType,
		&i.Payload,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsBySubmission = `-- name: ListArtifactsBySubmission :many
SELECT artifact_id, submission_id, artifact_type, payload, order_index, created_at
FROM app.submission_artifacts
WHERE submission_id = $1::uuid
ORDER BY order_index ASC, created_at ASC
`

func (q *Queries) ListArtifactsBySubmission(ctx context.Context, submissionID pgtype.UUID) ([]AppSubmissionArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppSubmissionArtifact
	for rows.Next() {
		var i AppSubmissionArtifact
		if err := rows.Scan(
			&i.ArtifactID,
			&i.SubmissionID,
			&i.ArtifactType,
			&i.Payload,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
