// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summaries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInterviewSummary = `-- name: CreateInterviewSummary :one
INSERT INTO app.interview_summaries (
    interview_id,
    overall_summary,
    strengths,
    areas_for_growth,
    suggested_next_steps,
    raw_llm_output
)
VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5,
    $6::jsonb
)
RETURNING interview_summary_id, interview_id, overall_summary, strengths, areas_for_growth, suggested_next_steps, raw_llm_output, created_at
`

type CreateInterviewSummaryParams struct {
	InterviewID        pgtype.UUID `db:"interview_id" json:"interviewId"`
	OverallSummary     pgtype.Text `db:"overall_summary" json:"overallSummary"`
	Strengths          pgtype.Text `db:"strengths" json:"strengths"`
	AreasForGrowth     pgtype.Text `db:"areas_for_growth" json:"areasForGrowth"`
	SuggestedNextSteps pgtype.Text `db:"suggested_next_steps" json:"suggestedNextSteps"`
	RawLlmOutput       []byte      `db:"raw_llm_output" json:"rawLlmOutput"`
}

func (q *Queries) CreateInterviewSummary(ctx context.Context, arg CreateInterviewSummaryParams) (AppInterviewSummary, error) {
	row := q.db.QueryRow(ctx, createInterviewSummary,
		arg.InterviewID,
		arg.OverallSummary,
		arg.Strengths,
		arg.AreasForGrowth,
		arg.SuggestedNextSteps,
		arg.RawLlmOutput,
	)
	var i AppInterviewSummary
	err := row.Scan(
		&i.InterviewSummaryID,
		&i.InterviewID,
		&i.OverallSummary,
		&i.Strengths,
		&i.AreasForGrowth,
		&i.SuggestedNextSteps,
		&i.RawLlmOutput,
		&i.CreatedAt,
	)
	return i, err
}

const getSummaryByInterviewID = `-- name: GetSummaryByInterviewID :one
SELECT interview_summary_id, interview_id, overall_summary, strengths, areas_for_growth, suggested_next_steps, raw_llm_output, created_at
FROM app.interview_summaries
WHERE interview_id = $1::uuid
`

func (q *Queries) GetSummaryByInterviewID(ctx context.Context, interviewID pgtype.UUID) (AppInterviewSummary, error) {
	row := q.db.QueryRow(ctx, getSummaryByInterviewID, interviewID)
	var i AppInterviewSummary
	err := row.Scan(
		&i.InterviewSummaryID,
		&i.InterviewID,
		&i.OverallSummary,
		&i.Strengths,
		&i.AreasForGrowth,
		&i.SuggestedNextSteps,
		&i.RawLlmOutput,
		&i.CreatedAt,
	)
	return i, err
}

const updateInterviewSummary = `-- name: UpdateInterviewSummary :one
UPDATE app.interview_summaries
SET overall_summary      = $1,
    strengths            = $2,
    areas_for_growth     = $3,
    suggested_next_steps = $4,
    raw_llm_output       = $5::jsonb
WHERE interview_id = $6::uuid
RETURNING interview_summary_id, interview_id, overall_summary, strengths, areas_for_growth, suggested_next_steps, raw_llm_output, created_at
`

type UpdateInterviewSummaryParams struct {
	OverallSummary     pgtype.Text `db:"overall_summary" json:"overallSummary"`
	Strengths          pgtype.Text `db:"strengths" json:"strengths"`
	AreasForGrowth     pgtype.Text `db:"areas_for_growth" json:"areasForGrowth"`
	SuggestedNextSteps pgtype.Text `db:"suggested_next_steps" json:"suggestedNextSteps"`
	RawLlmOutput       []byte      `db:"raw_llm_output" json:"rawLlmOutput"`
	InterviewID        pgtype.UUID `db:"interview_id" json:"interviewId"`
}

func (q *Queries) UpdateInterviewSummary(ctx context.Context, arg UpdateInterviewSummaryParams) (AppInterviewSummary, error) {
	row := q.db.QueryRow(ctx, updateInterviewSummary,
		arg.OverallSummary,
		arg.Strengths,
		arg.AreasForGrowth,
		arg.SuggestedNextSteps,
		arg.RawLlmOutput,
		arg.InterviewID,
	)
	var i AppInterviewSummary
	err := row.Scan(
		&i.InterviewSummaryID,
		&i.InterviewID,
		&i.OverallSummary,
		&i.Strengths,
		&i.AreasForGrowth,
		&i.SuggestedNextSteps,
		&i.RawLlmOutput,
		&i.CreatedAt,
	)
	return i, err
}
