// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teachers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO app.teachers (email, full_name, password_hash)
VALUES ($1, $2, $3)
RETURNING teacher_id, email, full_name, password_hash, is_enabled, created_at, updated_at
`

type CreateTeacherParams struct {
	Email        string      `db:"email" json:"email"`
	FullName     string      `db:"full_name" json:"fullName"`
	PasswordHash pgtype.Text `db:"password_hash" json:"passwordHash"`
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (AppTeacher, error) {
	row := q.db.QueryRow(ctx, createTeacher, arg.Email, arg.FullName, arg.PasswordHash)
	var i AppTeacher
	err := row.Scan(
		&i.TeacherID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacherByEmail = `-- name: GetTeacherByEmail :one
SELECT teacher_id, email, full_name, password_hash, is_enabled, created_at, updated_at
FROM app.teachers
WHERE email = $1
`

func (q *Queries) GetTeacherByEmail(ctx context.Context, email string) (AppTeacher, error) {
	row := q.db.QueryRow(ctx, getTeacherByEmail, email)
	var i AppTeacher
	err := row.Scan(
		&i.TeacherID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacherByID = `-- name: GetTeacherByID :one
SELECT teacher_id, email, full_name, password_hash, is_enabled, created_at, updated_at
FROM app.teachers
WHERE teacher_id = $1::uuid
`

func (q *Queries) GetTeacherByID(ctx context.Context, teacherID pgtype.UUID) (AppTeacher, error) {
	row := q.db.QueryRow(ctx, getTeacherByID, teacherID)
	var i AppTeacher
	err := row.Scan(
		&i.TeacherID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeachers = `-- name: ListTeachers :many
SELECT teacher_id, email, full_name, password_hash, is_enabled, created_at, updated_at
FROM app.teachers
ORDER BY created_at DESC
`

func (q *Queries) ListTeachers(ctx context.Context) ([]AppTeacher, error) {
	rows, err := q.db.Query(ctx, listTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppTeacher
	for rows.Next() {
		var i AppTeacher
		if err := rows.Scan(
			&i.TeacherID,
			&i.Email,
			&i.FullName,
			&i.PasswordHash,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
